// Code generated by ent, DO NOT EDIT.

package chatparticipant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"lazycat.community/appstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldID, id))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldConversationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldUserID, v))
}

// ClientUserID applies equality check predicate on the "client_user_id" field. It's identical to ClientUserIDEQ.
func ClientUserID(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldClientUserID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldDisplayName, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldAvatarURL, v))
}

// LastReadAt applies equality check predicate on the "last_read_at" field. It's identical to LastReadAtEQ.
func LastReadAt(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldLastReadAt, v))
}

// HiddenAt applies equality check predicate on the "hidden_at" field. It's identical to HiddenAtEQ.
func HiddenAt(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldHiddenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldUpdatedAt, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldConversationID, v))
}

// ActorTypeEQ applies the EQ predicate on the "actor_type" field.
func ActorTypeEQ(v ActorType) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldActorType, v))
}

// ActorTypeNEQ applies the NEQ predicate on the "actor_type" field.
func ActorTypeNEQ(v ActorType) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldActorType, v))
}

// ActorTypeIn applies the In predicate on the "actor_type" field.
func ActorTypeIn(vs ...ActorType) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldActorType, vs...))
}

// ActorTypeNotIn applies the NotIn predicate on the "actor_type" field.
func ActorTypeNotIn(vs ...ActorType) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldActorType, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldUserID, v))
}

// ClientUserIDEQ applies the EQ predicate on the "client_user_id" field.
func ClientUserIDEQ(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldClientUserID, v))
}

// ClientUserIDNEQ applies the NEQ predicate on the "client_user_id" field.
func ClientUserIDNEQ(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldClientUserID, v))
}

// ClientUserIDIn applies the In predicate on the "client_user_id" field.
func ClientUserIDIn(vs ...string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldClientUserID, vs...))
}

// ClientUserIDNotIn applies the NotIn predicate on the "client_user_id" field.
func ClientUserIDNotIn(vs ...string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldClientUserID, vs...))
}

// ClientUserIDGT applies the GT predicate on the "client_user_id" field.
func ClientUserIDGT(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldClientUserID, v))
}

// ClientUserIDGTE applies the GTE predicate on the "client_user_id" field.
func ClientUserIDGTE(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldClientUserID, v))
}

// ClientUserIDLT applies the LT predicate on the "client_user_id" field.
func ClientUserIDLT(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldClientUserID, v))
}

// ClientUserIDLTE applies the LTE predicate on the "client_user_id" field.
func ClientUserIDLTE(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldClientUserID, v))
}

// ClientUserIDContains applies the Contains predicate on the "client_user_id" field.
func ClientUserIDContains(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldContains(FieldClientUserID, v))
}

// ClientUserIDHasPrefix applies the HasPrefix predicate on the "client_user_id" field.
func ClientUserIDHasPrefix(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldHasPrefix(FieldClientUserID, v))
}

// ClientUserIDHasSuffix applies the HasSuffix predicate on the "client_user_id" field.
func ClientUserIDHasSuffix(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldHasSuffix(FieldClientUserID, v))
}

// ClientUserIDEqualFold applies the EqualFold predicate on the "client_user_id" field.
func ClientUserIDEqualFold(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEqualFold(FieldClientUserID, v))
}

// ClientUserIDContainsFold applies the ContainsFold predicate on the "client_user_id" field.
func ClientUserIDContainsFold(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldContainsFold(FieldClientUserID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldContainsFold(FieldDisplayName, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldContainsFold(FieldAvatarURL, v))
}

// LastReadAtEQ applies the EQ predicate on the "last_read_at" field.
func LastReadAtEQ(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldLastReadAt, v))
}

// LastReadAtNEQ applies the NEQ predicate on the "last_read_at" field.
func LastReadAtNEQ(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldLastReadAt, v))
}

// LastReadAtIn applies the In predicate on the "last_read_at" field.
func LastReadAtIn(vs ...time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldLastReadAt, vs...))
}

// LastReadAtNotIn applies the NotIn predicate on the "last_read_at" field.
func LastReadAtNotIn(vs ...time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldLastReadAt, vs...))
}

// LastReadAtGT applies the GT predicate on the "last_read_at" field.
func LastReadAtGT(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldLastReadAt, v))
}

// LastReadAtGTE applies the GTE predicate on the "last_read_at" field.
func LastReadAtGTE(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldLastReadAt, v))
}

// LastReadAtLT applies the LT predicate on the "last_read_at" field.
func LastReadAtLT(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldLastReadAt, v))
}

// LastReadAtLTE applies the LTE predicate on the "last_read_at" field.
func LastReadAtLTE(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldLastReadAt, v))
}

// LastReadAtIsNil applies the IsNil predicate on the "last_read_at" field.
func LastReadAtIsNil() predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIsNull(FieldLastReadAt))
}

// LastReadAtNotNil applies the NotNil predicate on the "last_read_at" field.
func LastReadAtNotNil() predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotNull(FieldLastReadAt))
}

// HiddenAtEQ applies the EQ predicate on the "hidden_at" field.
func HiddenAtEQ(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldHiddenAt, v))
}

// HiddenAtNEQ applies the NEQ predicate on the "hidden_at" field.
func HiddenAtNEQ(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldHiddenAt, v))
}

// HiddenAtIn applies the In predicate on the "hidden_at" field.
func HiddenAtIn(vs ...time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldHiddenAt, vs...))
}

// HiddenAtNotIn applies the NotIn predicate on the "hidden_at" field.
func HiddenAtNotIn(vs ...time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldHiddenAt, vs...))
}

// HiddenAtGT applies the GT predicate on the "hidden_at" field.
func HiddenAtGT(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldHiddenAt, v))
}

// HiddenAtGTE applies the GTE predicate on the "hidden_at" field.
func HiddenAtGTE(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldHiddenAt, v))
}

// HiddenAtLT applies the LT predicate on the "hidden_at" field.
func HiddenAtLT(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldHiddenAt, v))
}

// HiddenAtLTE applies the LTE predicate on the "hidden_at" field.
func HiddenAtLTE(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldHiddenAt, v))
}

// HiddenAtIsNil applies the IsNil predicate on the "hidden_at" field.
func HiddenAtIsNil() predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIsNull(FieldHiddenAt))
}

// HiddenAtNotNil applies the NotNil predicate on the "hidden_at" field.
func HiddenAtNotNil() predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotNull(FieldHiddenAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChatParticipant) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChatParticipant) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChatParticipant) predicate.ChatParticipant {
	return predicate.ChatParticipant(sql.NotPredicates(p))
}
