// Code generated by ent, DO NOT EDIT.

package clientsourceapp

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"lazycat.community/appstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldSourceID, v))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldExternalID, v))
}

// PackageID applies equality check predicate on the "package_id" field. It's identical to PackageIDEQ.
func PackageID(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldPackageID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldSlug, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldSummary, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldCategory, v))
}

// CategoryI18nJSON applies equality check predicate on the "category_i18n_json" field. It's identical to CategoryI18nJSONEQ.
func CategoryI18nJSON(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldCategoryI18nJSON, v))
}

// IconURL applies equality check predicate on the "icon_url" field. It's identical to IconURLEQ.
func IconURL(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldIconURL, v))
}

// InstallProtected applies equality check predicate on the "install_protected" field. It's identical to InstallProtectedEQ.
func InstallProtected(v bool) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldInstallProtected, v))
}

// ScreenshotsJSON applies equality check predicate on the "screenshots_json" field. It's identical to ScreenshotsJSONEQ.
func ScreenshotsJSON(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldScreenshotsJSON, v))
}

// LatestVersionJSON applies equality check predicate on the "latest_version_json" field. It's identical to LatestVersionJSONEQ.
func LatestVersionJSON(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldLatestVersionJSON, v))
}

// VersionsJSON applies equality check predicate on the "versions_json" field. It's identical to VersionsJSONEQ.
func VersionsJSON(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldVersionsJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldSourceID, vs...))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldExternalID, v))
}

// PackageIDEQ applies the EQ predicate on the "package_id" field.
func PackageIDEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldPackageID, v))
}

// PackageIDNEQ applies the NEQ predicate on the "package_id" field.
func PackageIDNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldPackageID, v))
}

// PackageIDIn applies the In predicate on the "package_id" field.
func PackageIDIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldPackageID, vs...))
}

// PackageIDNotIn applies the NotIn predicate on the "package_id" field.
func PackageIDNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldPackageID, vs...))
}

// PackageIDGT applies the GT predicate on the "package_id" field.
func PackageIDGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldPackageID, v))
}

// PackageIDGTE applies the GTE predicate on the "package_id" field.
func PackageIDGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldPackageID, v))
}

// PackageIDLT applies the LT predicate on the "package_id" field.
func PackageIDLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldPackageID, v))
}

// PackageIDLTE applies the LTE predicate on the "package_id" field.
func PackageIDLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldPackageID, v))
}

// PackageIDContains applies the Contains predicate on the "package_id" field.
func PackageIDContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldPackageID, v))
}

// PackageIDHasPrefix applies the HasPrefix predicate on the "package_id" field.
func PackageIDHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldPackageID, v))
}

// PackageIDHasSuffix applies the HasSuffix predicate on the "package_id" field.
func PackageIDHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldPackageID, v))
}

// PackageIDEqualFold applies the EqualFold predicate on the "package_id" field.
func PackageIDEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldPackageID, v))
}

// PackageIDContainsFold applies the ContainsFold predicate on the "package_id" field.
func PackageIDContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldPackageID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldSlug, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldSummary, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldCategory, v))
}

// CategoryI18nJSONEQ applies the EQ predicate on the "category_i18n_json" field.
func CategoryI18nJSONEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONNEQ applies the NEQ predicate on the "category_i18n_json" field.
func CategoryI18nJSONNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONIn applies the In predicate on the "category_i18n_json" field.
func CategoryI18nJSONIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldCategoryI18nJSON, vs...))
}

// CategoryI18nJSONNotIn applies the NotIn predicate on the "category_i18n_json" field.
func CategoryI18nJSONNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldCategoryI18nJSON, vs...))
}

// CategoryI18nJSONGT applies the GT predicate on the "category_i18n_json" field.
func CategoryI18nJSONGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONGTE applies the GTE predicate on the "category_i18n_json" field.
func CategoryI18nJSONGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONLT applies the LT predicate on the "category_i18n_json" field.
func CategoryI18nJSONLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONLTE applies the LTE predicate on the "category_i18n_json" field.
func CategoryI18nJSONLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONContains applies the Contains predicate on the "category_i18n_json" field.
func CategoryI18nJSONContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONHasPrefix applies the HasPrefix predicate on the "category_i18n_json" field.
func CategoryI18nJSONHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONHasSuffix applies the HasSuffix predicate on the "category_i18n_json" field.
func CategoryI18nJSONHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONEqualFold applies the EqualFold predicate on the "category_i18n_json" field.
func CategoryI18nJSONEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldCategoryI18nJSON, v))
}

// CategoryI18nJSONContainsFold applies the ContainsFold predicate on the "category_i18n_json" field.
func CategoryI18nJSONContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldCategoryI18nJSON, v))
}

// IconURLEQ applies the EQ predicate on the "icon_url" field.
func IconURLEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldIconURL, v))
}

// IconURLNEQ applies the NEQ predicate on the "icon_url" field.
func IconURLNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldIconURL, v))
}

// IconURLIn applies the In predicate on the "icon_url" field.
func IconURLIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldIconURL, vs...))
}

// IconURLNotIn applies the NotIn predicate on the "icon_url" field.
func IconURLNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldIconURL, vs...))
}

// IconURLGT applies the GT predicate on the "icon_url" field.
func IconURLGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldIconURL, v))
}

// IconURLGTE applies the GTE predicate on the "icon_url" field.
func IconURLGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldIconURL, v))
}

// IconURLLT applies the LT predicate on the "icon_url" field.
func IconURLLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldIconURL, v))
}

// IconURLLTE applies the LTE predicate on the "icon_url" field.
func IconURLLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldIconURL, v))
}

// IconURLContains applies the Contains predicate on the "icon_url" field.
func IconURLContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldIconURL, v))
}

// IconURLHasPrefix applies the HasPrefix predicate on the "icon_url" field.
func IconURLHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldIconURL, v))
}

// IconURLHasSuffix applies the HasSuffix predicate on the "icon_url" field.
func IconURLHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldIconURL, v))
}

// IconURLEqualFold applies the EqualFold predicate on the "icon_url" field.
func IconURLEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldIconURL, v))
}

// IconURLContainsFold applies the ContainsFold predicate on the "icon_url" field.
func IconURLContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldIconURL, v))
}

// InstallProtectedEQ applies the EQ predicate on the "install_protected" field.
func InstallProtectedEQ(v bool) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldInstallProtected, v))
}

// InstallProtectedNEQ applies the NEQ predicate on the "install_protected" field.
func InstallProtectedNEQ(v bool) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldInstallProtected, v))
}

// ScreenshotsJSONEQ applies the EQ predicate on the "screenshots_json" field.
func ScreenshotsJSONEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONNEQ applies the NEQ predicate on the "screenshots_json" field.
func ScreenshotsJSONNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONIn applies the In predicate on the "screenshots_json" field.
func ScreenshotsJSONIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldScreenshotsJSON, vs...))
}

// ScreenshotsJSONNotIn applies the NotIn predicate on the "screenshots_json" field.
func ScreenshotsJSONNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldScreenshotsJSON, vs...))
}

// ScreenshotsJSONGT applies the GT predicate on the "screenshots_json" field.
func ScreenshotsJSONGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONGTE applies the GTE predicate on the "screenshots_json" field.
func ScreenshotsJSONGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONLT applies the LT predicate on the "screenshots_json" field.
func ScreenshotsJSONLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONLTE applies the LTE predicate on the "screenshots_json" field.
func ScreenshotsJSONLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONContains applies the Contains predicate on the "screenshots_json" field.
func ScreenshotsJSONContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONHasPrefix applies the HasPrefix predicate on the "screenshots_json" field.
func ScreenshotsJSONHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONHasSuffix applies the HasSuffix predicate on the "screenshots_json" field.
func ScreenshotsJSONHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONEqualFold applies the EqualFold predicate on the "screenshots_json" field.
func ScreenshotsJSONEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldScreenshotsJSON, v))
}

// ScreenshotsJSONContainsFold applies the ContainsFold predicate on the "screenshots_json" field.
func ScreenshotsJSONContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldScreenshotsJSON, v))
}

// LatestVersionJSONEQ applies the EQ predicate on the "latest_version_json" field.
func LatestVersionJSONEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldLatestVersionJSON, v))
}

// LatestVersionJSONNEQ applies the NEQ predicate on the "latest_version_json" field.
func LatestVersionJSONNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldLatestVersionJSON, v))
}

// LatestVersionJSONIn applies the In predicate on the "latest_version_json" field.
func LatestVersionJSONIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldLatestVersionJSON, vs...))
}

// LatestVersionJSONNotIn applies the NotIn predicate on the "latest_version_json" field.
func LatestVersionJSONNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldLatestVersionJSON, vs...))
}

// LatestVersionJSONGT applies the GT predicate on the "latest_version_json" field.
func LatestVersionJSONGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldLatestVersionJSON, v))
}

// LatestVersionJSONGTE applies the GTE predicate on the "latest_version_json" field.
func LatestVersionJSONGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldLatestVersionJSON, v))
}

// LatestVersionJSONLT applies the LT predicate on the "latest_version_json" field.
func LatestVersionJSONLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldLatestVersionJSON, v))
}

// LatestVersionJSONLTE applies the LTE predicate on the "latest_version_json" field.
func LatestVersionJSONLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldLatestVersionJSON, v))
}

// LatestVersionJSONContains applies the Contains predicate on the "latest_version_json" field.
func LatestVersionJSONContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldLatestVersionJSON, v))
}

// LatestVersionJSONHasPrefix applies the HasPrefix predicate on the "latest_version_json" field.
func LatestVersionJSONHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldLatestVersionJSON, v))
}

// LatestVersionJSONHasSuffix applies the HasSuffix predicate on the "latest_version_json" field.
func LatestVersionJSONHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldLatestVersionJSON, v))
}

// LatestVersionJSONEqualFold applies the EqualFold predicate on the "latest_version_json" field.
func LatestVersionJSONEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldLatestVersionJSON, v))
}

// LatestVersionJSONContainsFold applies the ContainsFold predicate on the "latest_version_json" field.
func LatestVersionJSONContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldLatestVersionJSON, v))
}

// VersionsJSONEQ applies the EQ predicate on the "versions_json" field.
func VersionsJSONEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldVersionsJSON, v))
}

// VersionsJSONNEQ applies the NEQ predicate on the "versions_json" field.
func VersionsJSONNEQ(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldVersionsJSON, v))
}

// VersionsJSONIn applies the In predicate on the "versions_json" field.
func VersionsJSONIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldVersionsJSON, vs...))
}

// VersionsJSONNotIn applies the NotIn predicate on the "versions_json" field.
func VersionsJSONNotIn(vs ...string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldVersionsJSON, vs...))
}

// VersionsJSONGT applies the GT predicate on the "versions_json" field.
func VersionsJSONGT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldVersionsJSON, v))
}

// VersionsJSONGTE applies the GTE predicate on the "versions_json" field.
func VersionsJSONGTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldVersionsJSON, v))
}

// VersionsJSONLT applies the LT predicate on the "versions_json" field.
func VersionsJSONLT(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldVersionsJSON, v))
}

// VersionsJSONLTE applies the LTE predicate on the "versions_json" field.
func VersionsJSONLTE(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldVersionsJSON, v))
}

// VersionsJSONContains applies the Contains predicate on the "versions_json" field.
func VersionsJSONContains(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContains(FieldVersionsJSON, v))
}

// VersionsJSONHasPrefix applies the HasPrefix predicate on the "versions_json" field.
func VersionsJSONHasPrefix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasPrefix(FieldVersionsJSON, v))
}

// VersionsJSONHasSuffix applies the HasSuffix predicate on the "versions_json" field.
func VersionsJSONHasSuffix(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldHasSuffix(FieldVersionsJSON, v))
}

// VersionsJSONEqualFold applies the EqualFold predicate on the "versions_json" field.
func VersionsJSONEqualFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEqualFold(FieldVersionsJSON, v))
}

// VersionsJSONContainsFold applies the ContainsFold predicate on the "versions_json" field.
func VersionsJSONContainsFold(v string) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldContainsFold(FieldVersionsJSON, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSource applies the HasEdge predicate on the "source" edge.
func HasSource() predicate.ClientSourceApp {
	return predicate.ClientSourceApp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceWith applies the HasEdge predicate on the "source" edge with a given conditions (other predicates).
func HasSourceWith(preds ...predicate.ClientSource) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(func(s *sql.Selector) {
		step := newSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClientSourceApp) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClientSourceApp) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClientSourceApp) predicate.ClientSourceApp {
	return predicate.ClientSourceApp(sql.NotPredicates(p))
}
