// Code generated by ent, DO NOT EDIT.

package appscreenshot

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the appscreenshot type in the database.
	Label = "app_screenshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldUploaderID holds the string denoting the uploader_id field in the database.
	FieldUploaderID = "uploader_id"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldStoragePath holds the string denoting the storage_path field in the database.
	FieldStoragePath = "storage_path"
	// FieldCaption holds the string denoting the caption field in the database.
	FieldCaption = "caption"
	// FieldDeviceType holds the string denoting the device_type field in the database.
	FieldDeviceType = "device_type"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the appscreenshot in the database.
	Table = "app_screenshots"
)

// Columns holds all SQL columns for appscreenshot fields.
var Columns = []string{
	FieldID,
	FieldAppID,
	FieldUploaderID,
	FieldImageURL,
	FieldStoragePath,
	FieldCaption,
	FieldDeviceType,
	FieldSortOrder,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ImageURLValidator is a validator for the "image_url" field. It is called by the builders before save.
	ImageURLValidator func(string) error
	// DefaultStoragePath holds the default value on creation for the "storage_path" field.
	DefaultStoragePath string
	// DefaultCaption holds the default value on creation for the "caption" field.
	DefaultCaption string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// DeviceType defines the type for the "device_type" enum field.
type DeviceType string

// DeviceTypeDESKTOP is the default value of the DeviceType enum.
const DefaultDeviceType = DeviceTypeDESKTOP

// DeviceType values.
const (
	DeviceTypeDESKTOP DeviceType = "DESKTOP"
	DeviceTypeMOBILE  DeviceType = "MOBILE"
)

func (dt DeviceType) String() string {
	return string(dt)
}

// DeviceTypeValidator is a validator for the "device_type" field enum values. It is called by the builders before save.
func DeviceTypeValidator(dt DeviceType) error {
	switch dt {
	case DeviceTypeDESKTOP, DeviceTypeMOBILE:
		return nil
	default:
		return fmt.Errorf("appscreenshot: invalid enum value for device_type field: %q", dt)
	}
}

// OrderOption defines the ordering options for the AppScreenshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByUploaderID orders the results by the uploader_id field.
func ByUploaderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploaderID, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// ByStoragePath orders the results by the storage_path field.
func ByStoragePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoragePath, opts...).ToFunc()
}

// ByCaption orders the results by the caption field.
func ByCaption(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaption, opts...).ToFunc()
}

// ByDeviceType orders the results by the device_type field.
func ByDeviceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceType, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
