package: community.lazycat.app-store-server
version: 0.1.21
name: 喵喵私有商店服务端
description: 带嵌入式 Web 控制台的自托管 LPK 应用商店服务端。
author: czyt
license: MIT
homepage: https://github.com/lazycat-contrib/lazycat-community-appstore
min_os_version: 1.5.2
permissions:
  required:
    - net.internet
locales:
  zh:
    name: 喵喵私有商店服务端
    description: 带嵌入式 Web 控制台的自托管 LPK 应用商店服务端。
  en:
    name: MiaoMiao Private Store Server
    description: Self-hosted LPK app store server with embedded web console.
