// Code generated by ent, DO NOT EDIT.

package downstreamclientuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"lazycat.community/appstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldID, id))
}

// ClientUserID applies equality check predicate on the "client_user_id" field. It's identical to ClientUserIDEQ.
func ClientUserID(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldClientUserID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldDisplayName, v))
}

// SeenInComments applies equality check predicate on the "seen_in_comments" field. It's identical to SeenInCommentsEQ.
func SeenInComments(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldSeenInComments, v))
}

// SeenInWishes applies equality check predicate on the "seen_in_wishes" field. It's identical to SeenInWishesEQ.
func SeenInWishes(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldSeenInWishes, v))
}

// Blocked applies equality check predicate on the "blocked" field. It's identical to BlockedEQ.
func Blocked(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldBlocked, v))
}

// BlockReason applies equality check predicate on the "block_reason" field. It's identical to BlockReasonEQ.
func BlockReason(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldBlockReason, v))
}

// BlockedBy applies equality check predicate on the "blocked_by" field. It's identical to BlockedByEQ.
func BlockedBy(v int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldBlockedBy, v))
}

// BlockedAt applies equality check predicate on the "blocked_at" field. It's identical to BlockedAtEQ.
func BlockedAt(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldBlockedAt, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldFirstSeenAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientUserIDEQ applies the EQ predicate on the "client_user_id" field.
func ClientUserIDEQ(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldClientUserID, v))
}

// ClientUserIDNEQ applies the NEQ predicate on the "client_user_id" field.
func ClientUserIDNEQ(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldClientUserID, v))
}

// ClientUserIDIn applies the In predicate on the "client_user_id" field.
func ClientUserIDIn(vs ...string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldClientUserID, vs...))
}

// ClientUserIDNotIn applies the NotIn predicate on the "client_user_id" field.
func ClientUserIDNotIn(vs ...string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldClientUserID, vs...))
}

// ClientUserIDGT applies the GT predicate on the "client_user_id" field.
func ClientUserIDGT(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldClientUserID, v))
}

// ClientUserIDGTE applies the GTE predicate on the "client_user_id" field.
func ClientUserIDGTE(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldClientUserID, v))
}

// ClientUserIDLT applies the LT predicate on the "client_user_id" field.
func ClientUserIDLT(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldClientUserID, v))
}

// ClientUserIDLTE applies the LTE predicate on the "client_user_id" field.
func ClientUserIDLTE(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldClientUserID, v))
}

// ClientUserIDContains applies the Contains predicate on the "client_user_id" field.
func ClientUserIDContains(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldContains(FieldClientUserID, v))
}

// ClientUserIDHasPrefix applies the HasPrefix predicate on the "client_user_id" field.
func ClientUserIDHasPrefix(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldHasPrefix(FieldClientUserID, v))
}

// ClientUserIDHasSuffix applies the HasSuffix predicate on the "client_user_id" field.
func ClientUserIDHasSuffix(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldHasSuffix(FieldClientUserID, v))
}

// ClientUserIDEqualFold applies the EqualFold predicate on the "client_user_id" field.
func ClientUserIDEqualFold(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEqualFold(FieldClientUserID, v))
}

// ClientUserIDContainsFold applies the ContainsFold predicate on the "client_user_id" field.
func ClientUserIDContainsFold(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldContainsFold(FieldClientUserID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldContainsFold(FieldDisplayName, v))
}

// SeenInCommentsEQ applies the EQ predicate on the "seen_in_comments" field.
func SeenInCommentsEQ(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldSeenInComments, v))
}

// SeenInCommentsNEQ applies the NEQ predicate on the "seen_in_comments" field.
func SeenInCommentsNEQ(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldSeenInComments, v))
}

// SeenInWishesEQ applies the EQ predicate on the "seen_in_wishes" field.
func SeenInWishesEQ(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldSeenInWishes, v))
}

// SeenInWishesNEQ applies the NEQ predicate on the "seen_in_wishes" field.
func SeenInWishesNEQ(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldSeenInWishes, v))
}

// BlockedEQ applies the EQ predicate on the "blocked" field.
func BlockedEQ(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldBlocked, v))
}

// BlockedNEQ applies the NEQ predicate on the "blocked" field.
func BlockedNEQ(v bool) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldBlocked, v))
}

// BlockReasonEQ applies the EQ predicate on the "block_reason" field.
func BlockReasonEQ(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldBlockReason, v))
}

// BlockReasonNEQ applies the NEQ predicate on the "block_reason" field.
func BlockReasonNEQ(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldBlockReason, v))
}

// BlockReasonIn applies the In predicate on the "block_reason" field.
func BlockReasonIn(vs ...string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldBlockReason, vs...))
}

// BlockReasonNotIn applies the NotIn predicate on the "block_reason" field.
func BlockReasonNotIn(vs ...string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldBlockReason, vs...))
}

// BlockReasonGT applies the GT predicate on the "block_reason" field.
func BlockReasonGT(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldBlockReason, v))
}

// BlockReasonGTE applies the GTE predicate on the "block_reason" field.
func BlockReasonGTE(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldBlockReason, v))
}

// BlockReasonLT applies the LT predicate on the "block_reason" field.
func BlockReasonLT(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldBlockReason, v))
}

// BlockReasonLTE applies the LTE predicate on the "block_reason" field.
func BlockReasonLTE(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldBlockReason, v))
}

// BlockReasonContains applies the Contains predicate on the "block_reason" field.
func BlockReasonContains(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldContains(FieldBlockReason, v))
}

// BlockReasonHasPrefix applies the HasPrefix predicate on the "block_reason" field.
func BlockReasonHasPrefix(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldHasPrefix(FieldBlockReason, v))
}

// BlockReasonHasSuffix applies the HasSuffix predicate on the "block_reason" field.
func BlockReasonHasSuffix(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldHasSuffix(FieldBlockReason, v))
}

// BlockReasonEqualFold applies the EqualFold predicate on the "block_reason" field.
func BlockReasonEqualFold(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEqualFold(FieldBlockReason, v))
}

// BlockReasonContainsFold applies the ContainsFold predicate on the "block_reason" field.
func BlockReasonContainsFold(v string) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldContainsFold(FieldBlockReason, v))
}

// BlockedByEQ applies the EQ predicate on the "blocked_by" field.
func BlockedByEQ(v int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldBlockedBy, v))
}

// BlockedByNEQ applies the NEQ predicate on the "blocked_by" field.
func BlockedByNEQ(v int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldBlockedBy, v))
}

// BlockedByIn applies the In predicate on the "blocked_by" field.
func BlockedByIn(vs ...int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldBlockedBy, vs...))
}

// BlockedByNotIn applies the NotIn predicate on the "blocked_by" field.
func BlockedByNotIn(vs ...int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldBlockedBy, vs...))
}

// BlockedByGT applies the GT predicate on the "blocked_by" field.
func BlockedByGT(v int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldBlockedBy, v))
}

// BlockedByGTE applies the GTE predicate on the "blocked_by" field.
func BlockedByGTE(v int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldBlockedBy, v))
}

// BlockedByLT applies the LT predicate on the "blocked_by" field.
func BlockedByLT(v int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldBlockedBy, v))
}

// BlockedByLTE applies the LTE predicate on the "blocked_by" field.
func BlockedByLTE(v int) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldBlockedBy, v))
}

// BlockedByIsNil applies the IsNil predicate on the "blocked_by" field.
func BlockedByIsNil() predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIsNull(FieldBlockedBy))
}

// BlockedByNotNil applies the NotNil predicate on the "blocked_by" field.
func BlockedByNotNil() predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotNull(FieldBlockedBy))
}

// BlockedAtEQ applies the EQ predicate on the "blocked_at" field.
func BlockedAtEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldBlockedAt, v))
}

// BlockedAtNEQ applies the NEQ predicate on the "blocked_at" field.
func BlockedAtNEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldBlockedAt, v))
}

// BlockedAtIn applies the In predicate on the "blocked_at" field.
func BlockedAtIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldBlockedAt, vs...))
}

// BlockedAtNotIn applies the NotIn predicate on the "blocked_at" field.
func BlockedAtNotIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldBlockedAt, vs...))
}

// BlockedAtGT applies the GT predicate on the "blocked_at" field.
func BlockedAtGT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldBlockedAt, v))
}

// BlockedAtGTE applies the GTE predicate on the "blocked_at" field.
func BlockedAtGTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldBlockedAt, v))
}

// BlockedAtLT applies the LT predicate on the "blocked_at" field.
func BlockedAtLT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldBlockedAt, v))
}

// BlockedAtLTE applies the LTE predicate on the "blocked_at" field.
func BlockedAtLTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldBlockedAt, v))
}

// BlockedAtIsNil applies the IsNil predicate on the "blocked_at" field.
func BlockedAtIsNil() predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIsNull(FieldBlockedAt))
}

// BlockedAtNotNil applies the NotNil predicate on the "blocked_at" field.
func BlockedAtNotNil() predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotNull(FieldBlockedAt))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldFirstSeenAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DownstreamClientUser) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DownstreamClientUser) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DownstreamClientUser) predicate.DownstreamClientUser {
	return predicate.DownstreamClientUser(sql.NotPredicates(p))
}
