// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/ad"
)

// AdCreate is the builder for creating a Ad entity.
type AdCreate struct {
	config
	mutation *AdMutation
	hooks    []Hook
}

// SetEnabled sets the "enabled" field.
func (_c *AdCreate) SetEnabled(v bool) *AdCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AdCreate) SetNillableEnabled(v *bool) *AdCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *AdCreate) SetTitle(v string) *AdCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *AdCreate) SetNillableTitle(v *string) *AdCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *AdCreate) SetBody(v string) *AdCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *AdCreate) SetNillableBody(v *string) *AdCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *AdCreate) SetImageURL(v string) *AdCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *AdCreate) SetNillableImageURL(v *string) *AdCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetLinkLabel sets the "link_label" field.
func (_c *AdCreate) SetLinkLabel(v string) *AdCreate {
	_c.mutation.SetLinkLabel(v)
	return _c
}

// SetNillableLinkLabel sets the "link_label" field if the given value is not nil.
func (_c *AdCreate) SetNillableLinkLabel(v *string) *AdCreate {
	if v != nil {
		_c.SetLinkLabel(*v)
	}
	return _c
}

// SetLinkURL sets the "link_url" field.
func (_c *AdCreate) SetLinkURL(v string) *AdCreate {
	_c.mutation.SetLinkURL(v)
	return _c
}

// SetNillableLinkURL sets the "link_url" field if the given value is not nil.
func (_c *AdCreate) SetNillableLinkURL(v *string) *AdCreate {
	if v != nil {
		_c.SetLinkURL(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *AdCreate) SetStartsAt(v time.Time) *AdCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *AdCreate) SetNillableStartsAt(v *time.Time) *AdCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *AdCreate) SetEndsAt(v time.Time) *AdCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *AdCreate) SetNillableEndsAt(v *time.Time) *AdCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *AdCreate) SetSortOrder(v int) *AdCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *AdCreate) SetNillableSortOrder(v *int) *AdCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdCreate) SetCreatedAt(v time.Time) *AdCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdCreate) SetNillableCreatedAt(v *time.Time) *AdCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdCreate) SetUpdatedAt(v time.Time) *AdCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdCreate) SetNillableUpdatedAt(v *time.Time) *AdCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AdMutation object of the builder.
func (_c *AdCreate) Mutation() *AdMutation {
	return _c.mutation
}

// Save creates the Ad in the database.
func (_c *AdCreate) Save(ctx context.Context) (*Ad, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdCreate) SaveX(ctx context.Context) *Ad {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := ad.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := ad.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Body(); !ok {
		v := ad.DefaultBody
		_c.mutation.SetBody(v)
	}
	if _, ok := _c.mutation.ImageURL(); !ok {
		v := ad.DefaultImageURL
		_c.mutation.SetImageURL(v)
	}
	if _, ok := _c.mutation.LinkLabel(); !ok {
		v := ad.DefaultLinkLabel
		_c.mutation.SetLinkLabel(v)
	}
	if _, ok := _c.mutation.LinkURL(); !ok {
		v := ad.DefaultLinkURL
		_c.mutation.SetLinkURL(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := ad.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ad.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ad.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdCreate) check() error {
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Ad.enabled"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Ad.title"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Ad.body"`)}
	}
	if _, ok := _c.mutation.ImageURL(); !ok {
		return &ValidationError{Name: "image_url", err: errors.New(`ent: missing required field "Ad.image_url"`)}
	}
	if _, ok := _c.mutation.LinkLabel(); !ok {
		return &ValidationError{Name: "link_label", err: errors.New(`ent: missing required field "Ad.link_label"`)}
	}
	if _, ok := _c.mutation.LinkURL(); !ok {
		return &ValidationError{Name: "link_url", err: errors.New(`ent: missing required field "Ad.link_url"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Ad.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ad.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ad.updated_at"`)}
	}
	return nil
}

func (_c *AdCreate) sqlSave(ctx context.Context) (*Ad, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdCreate) createSpec() (*Ad, *sqlgraph.CreateSpec) {
	var (
		_node = &Ad{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ad.Table, sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(ad.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(ad.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(ad.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(ad.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := _c.mutation.LinkLabel(); ok {
		_spec.SetField(ad.FieldLinkLabel, field.TypeString, value)
		_node.LinkLabel = value
	}
	if value, ok := _c.mutation.LinkURL(); ok {
		_spec.SetField(ad.FieldLinkURL, field.TypeString, value)
		_node.LinkURL = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(ad.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = &value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(ad.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(ad.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ad.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ad.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AdCreateBulk is the builder for creating many Ad entities in bulk.
type AdCreateBulk struct {
	config
	err      error
	builders []*AdCreate
}

// Save creates the Ad entities in the database.
func (_c *AdCreateBulk) Save(ctx context.Context) ([]*Ad, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ad, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdCreateBulk) SaveX(ctx context.Context) []*Ad {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
