// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/ad"
	"lazycat.community/appstore/ent/predicate"
)

// AdUpdate is the builder for updating Ad entities.
type AdUpdate struct {
	config
	hooks    []Hook
	mutation *AdMutation
}

// Where appends a list predicates to the AdUpdate builder.
func (_u *AdUpdate) Where(ps ...predicate.Ad) *AdUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdUpdate) SetEnabled(v bool) *AdUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdUpdate) SetNillableEnabled(v *bool) *AdUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AdUpdate) SetTitle(v string) *AdUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AdUpdate) SetNillableTitle(v *string) *AdUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *AdUpdate) SetBody(v string) *AdUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *AdUpdate) SetNillableBody(v *string) *AdUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *AdUpdate) SetImageURL(v string) *AdUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *AdUpdate) SetNillableImageURL(v *string) *AdUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// SetLinkLabel sets the "link_label" field.
func (_u *AdUpdate) SetLinkLabel(v string) *AdUpdate {
	_u.mutation.SetLinkLabel(v)
	return _u
}

// SetNillableLinkLabel sets the "link_label" field if the given value is not nil.
func (_u *AdUpdate) SetNillableLinkLabel(v *string) *AdUpdate {
	if v != nil {
		_u.SetLinkLabel(*v)
	}
	return _u
}

// SetLinkURL sets the "link_url" field.
func (_u *AdUpdate) SetLinkURL(v string) *AdUpdate {
	_u.mutation.SetLinkURL(v)
	return _u
}

// SetNillableLinkURL sets the "link_url" field if the given value is not nil.
func (_u *AdUpdate) SetNillableLinkURL(v *string) *AdUpdate {
	if v != nil {
		_u.SetLinkURL(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *AdUpdate) SetStartsAt(v time.Time) *AdUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *AdUpdate) SetNillableStartsAt(v *time.Time) *AdUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *AdUpdate) ClearStartsAt() *AdUpdate {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *AdUpdate) SetEndsAt(v time.Time) *AdUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *AdUpdate) SetNillableEndsAt(v *time.Time) *AdUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *AdUpdate) ClearEndsAt() *AdUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AdUpdate) SetSortOrder(v int) *AdUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AdUpdate) SetNillableSortOrder(v *int) *AdUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AdUpdate) AddSortOrder(v int) *AdUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdUpdate) SetCreatedAt(v time.Time) *AdUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdUpdate) SetNillableCreatedAt(v *time.Time) *AdUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdUpdate) SetUpdatedAt(v time.Time) *AdUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdMutation object of the builder.
func (_u *AdUpdate) Mutation() *AdMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ad.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ad.Table, ad.Columns, sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ad.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(ad.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(ad.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(ad.FieldImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkLabel(); ok {
		_spec.SetField(ad.FieldLinkLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkURL(); ok {
		_spec.SetField(ad.FieldLinkURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(ad.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(ad.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(ad.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(ad.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(ad.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(ad.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(ad.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ad.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ad.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdUpdateOne is the builder for updating a single Ad entity.
type AdUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdMutation
}

// SetEnabled sets the "enabled" field.
func (_u *AdUpdateOne) SetEnabled(v bool) *AdUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableEnabled(v *bool) *AdUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AdUpdateOne) SetTitle(v string) *AdUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableTitle(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *AdUpdateOne) SetBody(v string) *AdUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableBody(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *AdUpdateOne) SetImageURL(v string) *AdUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableImageURL(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// SetLinkLabel sets the "link_label" field.
func (_u *AdUpdateOne) SetLinkLabel(v string) *AdUpdateOne {
	_u.mutation.SetLinkLabel(v)
	return _u
}

// SetNillableLinkLabel sets the "link_label" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableLinkLabel(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetLinkLabel(*v)
	}
	return _u
}

// SetLinkURL sets the "link_url" field.
func (_u *AdUpdateOne) SetLinkURL(v string) *AdUpdateOne {
	_u.mutation.SetLinkURL(v)
	return _u
}

// SetNillableLinkURL sets the "link_url" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableLinkURL(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetLinkURL(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *AdUpdateOne) SetStartsAt(v time.Time) *AdUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableStartsAt(v *time.Time) *AdUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *AdUpdateOne) ClearStartsAt() *AdUpdateOne {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *AdUpdateOne) SetEndsAt(v time.Time) *AdUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableEndsAt(v *time.Time) *AdUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *AdUpdateOne) ClearEndsAt() *AdUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AdUpdateOne) SetSortOrder(v int) *AdUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableSortOrder(v *int) *AdUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AdUpdateOne) AddSortOrder(v int) *AdUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdUpdateOne) SetCreatedAt(v time.Time) *AdUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableCreatedAt(v *time.Time) *AdUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdUpdateOne) SetUpdatedAt(v time.Time) *AdUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdMutation object of the builder.
func (_u *AdUpdateOne) Mutation() *AdMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdUpdate builder.
func (_u *AdUpdateOne) Where(ps ...predicate.Ad) *AdUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdUpdateOne) Select(field string, fields ...string) *AdUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ad entity.
func (_u *AdUpdateOne) Save(ctx context.Context) (*Ad, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdUpdateOne) SaveX(ctx context.Context) *Ad {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ad.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdUpdateOne) sqlSave(ctx context.Context) (_node *Ad, err error) {
	_spec := sqlgraph.NewUpdateSpec(ad.Table, ad.Columns, sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ad.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ad.FieldID)
		for _, f := range fields {
			if !ad.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ad.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ad.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(ad.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(ad.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(ad.FieldImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkLabel(); ok {
		_spec.SetField(ad.FieldLinkLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkURL(); ok {
		_spec.SetField(ad.FieldLinkURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(ad.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(ad.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(ad.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(ad.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(ad.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(ad.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(ad.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ad.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Ad{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ad.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
