// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/announcement"
	"lazycat.community/appstore/ent/predicate"
)

// AnnouncementUpdate is the builder for updating Announcement entities.
type AnnouncementUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementMutation
}

// Where appends a list predicates to the AnnouncementUpdate builder.
func (_u *AnnouncementUpdate) Where(ps ...predicate.Announcement) *AnnouncementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AnnouncementUpdate) SetEnabled(v bool) *AnnouncementUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableEnabled(v *bool) *AnnouncementUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *AnnouncementUpdate) SetLevel(v announcement.Level) *AnnouncementUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableLevel(v *announcement.Level) *AnnouncementUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AnnouncementUpdate) SetTitle(v string) *AnnouncementUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableTitle(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *AnnouncementUpdate) SetBody(v string) *AnnouncementUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableBody(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetLinkLabel sets the "link_label" field.
func (_u *AnnouncementUpdate) SetLinkLabel(v string) *AnnouncementUpdate {
	_u.mutation.SetLinkLabel(v)
	return _u
}

// SetNillableLinkLabel sets the "link_label" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableLinkLabel(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetLinkLabel(*v)
	}
	return _u
}

// SetLinkURL sets the "link_url" field.
func (_u *AnnouncementUpdate) SetLinkURL(v string) *AnnouncementUpdate {
	_u.mutation.SetLinkURL(v)
	return _u
}

// SetNillableLinkURL sets the "link_url" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableLinkURL(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetLinkURL(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *AnnouncementUpdate) SetStartsAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableStartsAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *AnnouncementUpdate) ClearStartsAt() *AnnouncementUpdate {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *AnnouncementUpdate) SetEndsAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableEndsAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *AnnouncementUpdate) ClearEndsAt() *AnnouncementUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AnnouncementUpdate) SetSortOrder(v int) *AnnouncementUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableSortOrder(v *int) *AnnouncementUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AnnouncementUpdate) AddSortOrder(v int) *AnnouncementUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AnnouncementUpdate) SetCreatedAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableCreatedAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnnouncementUpdate) SetUpdatedAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_u *AnnouncementUpdate) Mutation() *AnnouncementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnnouncementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := announcement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementUpdate) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := announcement.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Announcement.level": %w`, err)}
		}
	}
	return nil
}

func (_u *AnnouncementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcement.Table, announcement.Columns, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(announcement.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(announcement.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(announcement.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(announcement.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkLabel(); ok {
		_spec.SetField(announcement.FieldLinkLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkURL(); ok {
		_spec.SetField(announcement.FieldLinkURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(announcement.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(announcement.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(announcement.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(announcement.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(announcement.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(announcement.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(announcement.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(announcement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementUpdateOne is the builder for updating a single Announcement entity.
type AnnouncementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementMutation
}

// SetEnabled sets the "enabled" field.
func (_u *AnnouncementUpdateOne) SetEnabled(v bool) *AnnouncementUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableEnabled(v *bool) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *AnnouncementUpdateOne) SetLevel(v announcement.Level) *AnnouncementUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableLevel(v *announcement.Level) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AnnouncementUpdateOne) SetTitle(v string) *AnnouncementUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableTitle(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *AnnouncementUpdateOne) SetBody(v string) *AnnouncementUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableBody(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetLinkLabel sets the "link_label" field.
func (_u *AnnouncementUpdateOne) SetLinkLabel(v string) *AnnouncementUpdateOne {
	_u.mutation.SetLinkLabel(v)
	return _u
}

// SetNillableLinkLabel sets the "link_label" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableLinkLabel(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetLinkLabel(*v)
	}
	return _u
}

// SetLinkURL sets the "link_url" field.
func (_u *AnnouncementUpdateOne) SetLinkURL(v string) *AnnouncementUpdateOne {
	_u.mutation.SetLinkURL(v)
	return _u
}

// SetNillableLinkURL sets the "link_url" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableLinkURL(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetLinkURL(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *AnnouncementUpdateOne) SetStartsAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableStartsAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *AnnouncementUpdateOne) ClearStartsAt() *AnnouncementUpdateOne {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *AnnouncementUpdateOne) SetEndsAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableEndsAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *AnnouncementUpdateOne) ClearEndsAt() *AnnouncementUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AnnouncementUpdateOne) SetSortOrder(v int) *AnnouncementUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableSortOrder(v *int) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AnnouncementUpdateOne) AddSortOrder(v int) *AnnouncementUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AnnouncementUpdateOne) SetCreatedAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableCreatedAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnnouncementUpdateOne) SetUpdatedAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_u *AnnouncementUpdateOne) Mutation() *AnnouncementMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnnouncementUpdate builder.
func (_u *AnnouncementUpdateOne) Where(ps ...predicate.Announcement) *AnnouncementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementUpdateOne) Select(field string, fields ...string) *AnnouncementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Announcement entity.
func (_u *AnnouncementUpdateOne) Save(ctx context.Context) (*Announcement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementUpdateOne) SaveX(ctx context.Context) *Announcement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnnouncementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := announcement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementUpdateOne) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := announcement.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Announcement.level": %w`, err)}
		}
	}
	return nil
}

func (_u *AnnouncementUpdateOne) sqlSave(ctx context.Context) (_node *Announcement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcement.Table, announcement.Columns, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Announcement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcement.FieldID)
		for _, f := range fields {
			if !announcement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(announcement.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(announcement.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(announcement.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(announcement.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkLabel(); ok {
		_spec.SetField(announcement.FieldLinkLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkURL(); ok {
		_spec.SetField(announcement.FieldLinkURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(announcement.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(announcement.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(announcement.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(announcement.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(announcement.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(announcement.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(announcement.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(announcement.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Announcement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
