// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/apptag"
)

// AppTagCreate is the builder for creating a AppTag entity.
type AppTagCreate struct {
	config
	mutation *AppTagMutation
	hooks    []Hook
}

// SetAppID sets the "app_id" field.
func (_c *AppTagCreate) SetAppID(v int) *AppTagCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetTagID sets the "tag_id" field.
func (_c *AppTagCreate) SetTagID(v int) *AppTagCreate {
	_c.mutation.SetTagID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppTagCreate) SetCreatedAt(v time.Time) *AppTagCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppTagCreate) SetNillableCreatedAt(v *time.Time) *AppTagCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AppTagMutation object of the builder.
func (_c *AppTagCreate) Mutation() *AppTagMutation {
	return _c.mutation
}

// Save creates the AppTag in the database.
func (_c *AppTagCreate) Save(ctx context.Context) (*AppTag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppTagCreate) SaveX(ctx context.Context) *AppTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppTagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppTagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppTagCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apptag.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppTagCreate) check() error {
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "AppTag.app_id"`)}
	}
	if _, ok := _c.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "AppTag.tag_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppTag.created_at"`)}
	}
	return nil
}

func (_c *AppTagCreate) sqlSave(ctx context.Context) (*AppTag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppTagCreate) createSpec() (*AppTag, *sqlgraph.CreateSpec) {
	var (
		_node = &AppTag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apptag.Table, sqlgraph.NewFieldSpec(apptag.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(apptag.FieldAppID, field.TypeInt, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.TagID(); ok {
		_spec.SetField(apptag.FieldTagID, field.TypeInt, value)
		_node.TagID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apptag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AppTagCreateBulk is the builder for creating many AppTag entities in bulk.
type AppTagCreateBulk struct {
	config
	err      error
	builders []*AppTagCreate
}

// Save creates the AppTag entities in the database.
func (_c *AppTagCreateBulk) Save(ctx context.Context) ([]*AppTag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppTag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppTagCreateBulk) SaveX(ctx context.Context) []*AppTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppTagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppTagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
