// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/chatconversation"
	"lazycat.community/appstore/ent/predicate"
)

// ChatConversationUpdate is the builder for updating ChatConversation entities.
type ChatConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ChatConversationMutation
}

// Where appends a list predicates to the ChatConversationUpdate builder.
func (_u *ChatConversationUpdate) Where(ps ...predicate.ChatConversation) *ChatConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ChatConversationUpdate) SetAppID(v int) *ChatConversationUpdate {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableAppID(v *int) *ChatConversationUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *ChatConversationUpdate) AddAppID(v int) *ChatConversationUpdate {
	_u.mutation.AddAppID(v)
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *ChatConversationUpdate) ClearAppID() *ChatConversationUpdate {
	_u.mutation.ClearAppID()
	return _u
}

// SetTopic sets the "topic" field.
func (_u *ChatConversationUpdate) SetTopic(v string) *ChatConversationUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableTopic(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetLastMessageBody sets the "last_message_body" field.
func (_u *ChatConversationUpdate) SetLastMessageBody(v string) *ChatConversationUpdate {
	_u.mutation.SetLastMessageBody(v)
	return _u
}

// SetNillableLastMessageBody sets the "last_message_body" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableLastMessageBody(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetLastMessageBody(*v)
	}
	return _u
}

// SetLastMessageSenderName sets the "last_message_sender_name" field.
func (_u *ChatConversationUpdate) SetLastMessageSenderName(v string) *ChatConversationUpdate {
	_u.mutation.SetLastMessageSenderName(v)
	return _u
}

// SetNillableLastMessageSenderName sets the "last_message_sender_name" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableLastMessageSenderName(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetLastMessageSenderName(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ChatConversationUpdate) SetLastMessageAt(v time.Time) *ChatConversationUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableLastMessageAt(v *time.Time) *ChatConversationUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *ChatConversationUpdate) ClearLastMessageAt() *ChatConversationUpdate {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ChatConversationUpdate) SetCreatedAt(v time.Time) *ChatConversationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableCreatedAt(v *time.Time) *ChatConversationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatConversationUpdate) SetUpdatedAt(v time.Time) *ChatConversationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_u *ChatConversationUpdate) Mutation() *ChatConversationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatConversationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatConversationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ChatConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(chatconversation.Table, chatconversation.Columns, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(chatconversation.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(chatconversation.FieldAppID, field.TypeInt, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(chatconversation.FieldAppID, field.TypeInt)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(chatconversation.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageBody(); ok {
		_spec.SetField(chatconversation.FieldLastMessageBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageSenderName(); ok {
		_spec.SetField(chatconversation.FieldLastMessageSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(chatconversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(chatconversation.FieldLastMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(chatconversation.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatConversationUpdateOne is the builder for updating a single ChatConversation entity.
type ChatConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatConversationMutation
}

// SetAppID sets the "app_id" field.
func (_u *ChatConversationUpdateOne) SetAppID(v int) *ChatConversationUpdateOne {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableAppID(v *int) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *ChatConversationUpdateOne) AddAppID(v int) *ChatConversationUpdateOne {
	_u.mutation.AddAppID(v)
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *ChatConversationUpdateOne) ClearAppID() *ChatConversationUpdateOne {
	_u.mutation.ClearAppID()
	return _u
}

// SetTopic sets the "topic" field.
func (_u *ChatConversationUpdateOne) SetTopic(v string) *ChatConversationUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableTopic(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetLastMessageBody sets the "last_message_body" field.
func (_u *ChatConversationUpdateOne) SetLastMessageBody(v string) *ChatConversationUpdateOne {
	_u.mutation.SetLastMessageBody(v)
	return _u
}

// SetNillableLastMessageBody sets the "last_message_body" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableLastMessageBody(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageBody(*v)
	}
	return _u
}

// SetLastMessageSenderName sets the "last_message_sender_name" field.
func (_u *ChatConversationUpdateOne) SetLastMessageSenderName(v string) *ChatConversationUpdateOne {
	_u.mutation.SetLastMessageSenderName(v)
	return _u
}

// SetNillableLastMessageSenderName sets the "last_message_sender_name" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableLastMessageSenderName(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageSenderName(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ChatConversationUpdateOne) SetLastMessageAt(v time.Time) *ChatConversationUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableLastMessageAt(v *time.Time) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *ChatConversationUpdateOne) ClearLastMessageAt() *ChatConversationUpdateOne {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ChatConversationUpdateOne) SetCreatedAt(v time.Time) *ChatConversationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableCreatedAt(v *time.Time) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatConversationUpdateOne) SetUpdatedAt(v time.Time) *ChatConversationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_u *ChatConversationUpdateOne) Mutation() *ChatConversationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChatConversationUpdate builder.
func (_u *ChatConversationUpdateOne) Where(ps ...predicate.ChatConversation) *ChatConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatConversationUpdateOne) Select(field string, fields ...string) *ChatConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatConversation entity.
func (_u *ChatConversationUpdateOne) Save(ctx context.Context) (*ChatConversation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatConversationUpdateOne) SaveX(ctx context.Context) *ChatConversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatConversationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ChatConversationUpdateOne) sqlSave(ctx context.Context) (_node *ChatConversation, err error) {
	_spec := sqlgraph.NewUpdateSpec(chatconversation.Table, chatconversation.Columns, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatConversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatconversation.FieldID)
		for _, f := range fields {
			if !chatconversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatconversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(chatconversation.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(chatconversation.FieldAppID, field.TypeInt, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(chatconversation.FieldAppID, field.TypeInt)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(chatconversation.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageBody(); ok {
		_spec.SetField(chatconversation.FieldLastMessageBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageSenderName(); ok {
		_spec.SetField(chatconversation.FieldLastMessageSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(chatconversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(chatconversation.FieldLastMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(chatconversation.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ChatConversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
