// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"lazycat.community/appstore/ent/chatmessage"
)

// ChatMessage is the model entity for the ChatMessage schema.
type ChatMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ConversationID holds the value of the "conversation_id" field.
	ConversationID int `json:"conversation_id,omitempty"`
	// SenderType holds the value of the "sender_type" field.
	SenderType chatmessage.SenderType `json:"sender_type,omitempty"`
	// SenderUserID holds the value of the "sender_user_id" field.
	SenderUserID int `json:"sender_user_id,omitempty"`
	// SenderClientUserID holds the value of the "sender_client_user_id" field.
	SenderClientUserID string `json:"sender_client_user_id,omitempty"`
	// SenderName holds the value of the "sender_name" field.
	SenderName string `json:"sender_name,omitempty"`
	// SenderAvatarURL holds the value of the "sender_avatar_url" field.
	SenderAvatarURL string `json:"sender_avatar_url,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Deleted holds the value of the "deleted" field.
	Deleted bool `json:"deleted,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatmessage.FieldDeleted:
			values[i] = new(sql.NullBool)
		case chatmessage.FieldID, chatmessage.FieldConversationID, chatmessage.FieldSenderUserID:
			values[i] = new(sql.NullInt64)
		case chatmessage.FieldSenderType, chatmessage.FieldSenderClientUserID, chatmessage.FieldSenderName, chatmessage.FieldSenderAvatarURL, chatmessage.FieldBody:
			values[i] = new(sql.NullString)
		case chatmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatMessage fields.
func (_m *ChatMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chatmessage.FieldConversationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value.Valid {
				_m.ConversationID = int(value.Int64)
			}
		case chatmessage.FieldSenderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_type", values[i])
			} else if value.Valid {
				_m.SenderType = chatmessage.SenderType(value.String)
			}
		case chatmessage.FieldSenderUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sender_user_id", values[i])
			} else if value.Valid {
				_m.SenderUserID = int(value.Int64)
			}
		case chatmessage.FieldSenderClientUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_client_user_id", values[i])
			} else if value.Valid {
				_m.SenderClientUserID = value.String
			}
		case chatmessage.FieldSenderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_name", values[i])
			} else if value.Valid {
				_m.SenderName = value.String
			}
		case chatmessage.FieldSenderAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_avatar_url", values[i])
			} else if value.Valid {
				_m.SenderAvatarURL = value.String
			}
		case chatmessage.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case chatmessage.FieldDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deleted", values[i])
			} else if value.Valid {
				_m.Deleted = value.Bool
			}
		case chatmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatMessage.
// This includes values selected through modifiers, order, etc.
func (_m *ChatMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChatMessage.
// Note that you need to call ChatMessage.Unwrap() before calling this method if this ChatMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatMessage) Update() *ChatMessageUpdateOne {
	return NewChatMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatMessage) Unwrap() *ChatMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatMessage) String() string {
	var builder strings.Builder
	builder.WriteString("ChatMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("conversation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConversationID))
	builder.WriteString(", ")
	builder.WriteString("sender_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SenderType))
	builder.WriteString(", ")
	builder.WriteString("sender_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SenderUserID))
	builder.WriteString(", ")
	builder.WriteString("sender_client_user_id=")
	builder.WriteString(_m.SenderClientUserID)
	builder.WriteString(", ")
	builder.WriteString("sender_name=")
	builder.WriteString(_m.SenderName)
	builder.WriteString(", ")
	builder.WriteString("sender_avatar_url=")
	builder.WriteString(_m.SenderAvatarURL)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Deleted))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatMessages is a parsable slice of ChatMessage.
type ChatMessages []*ChatMessage
