// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"lazycat.community/appstore/ent/clientsyncsetting"
)

// ClientSyncSetting is the model entity for the ClientSyncSetting schema.
type ClientSyncSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// AutoSyncEnabled holds the value of the "auto_sync_enabled" field.
	AutoSyncEnabled bool `json:"auto_sync_enabled,omitempty"`
	// AutoSyncIntervalMinutes holds the value of the "auto_sync_interval_minutes" field.
	AutoSyncIntervalMinutes int `json:"auto_sync_interval_minutes,omitempty"`
	// SyncOnStartup holds the value of the "sync_on_startup" field.
	SyncOnStartup bool `json:"sync_on_startup,omitempty"`
	// LastAutoSyncAt holds the value of the "last_auto_sync_at" field.
	LastAutoSyncAt *time.Time `json:"last_auto_sync_at,omitempty"`
	// LastAutoSyncStatus holds the value of the "last_auto_sync_status" field.
	LastAutoSyncStatus *clientsyncsetting.LastAutoSyncStatus `json:"last_auto_sync_status,omitempty"`
	// LastAutoSyncError holds the value of the "last_auto_sync_error" field.
	LastAutoSyncError *string `json:"last_auto_sync_error,omitempty"`
	// AutoUpdateEnabled holds the value of the "auto_update_enabled" field.
	AutoUpdateEnabled bool `json:"auto_update_enabled,omitempty"`
	// AutoUpdateIntervalMinutes holds the value of the "auto_update_interval_minutes" field.
	AutoUpdateIntervalMinutes int `json:"auto_update_interval_minutes,omitempty"`
	// LastAutoUpdateAt holds the value of the "last_auto_update_at" field.
	LastAutoUpdateAt *time.Time `json:"last_auto_update_at,omitempty"`
	// LastAutoUpdateStatus holds the value of the "last_auto_update_status" field.
	LastAutoUpdateStatus *clientsyncsetting.LastAutoUpdateStatus `json:"last_auto_update_status,omitempty"`
	// LastAutoUpdateError holds the value of the "last_auto_update_error" field.
	LastAutoUpdateError *string `json:"last_auto_update_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClientSyncSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clientsyncsetting.FieldAutoSyncEnabled, clientsyncsetting.FieldSyncOnStartup, clientsyncsetting.FieldAutoUpdateEnabled:
			values[i] = new(sql.NullBool)
		case clientsyncsetting.FieldID, clientsyncsetting.FieldAutoSyncIntervalMinutes, clientsyncsetting.FieldAutoUpdateIntervalMinutes:
			values[i] = new(sql.NullInt64)
		case clientsyncsetting.FieldUserID, clientsyncsetting.FieldLastAutoSyncStatus, clientsyncsetting.FieldLastAutoSyncError, clientsyncsetting.FieldLastAutoUpdateStatus, clientsyncsetting.FieldLastAutoUpdateError:
			values[i] = new(sql.NullString)
		case clientsyncsetting.FieldLastAutoSyncAt, clientsyncsetting.FieldLastAutoUpdateAt, clientsyncsetting.FieldCreatedAt, clientsyncsetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClientSyncSetting fields.
func (_m *ClientSyncSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clientsyncsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case clientsyncsetting.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case clientsyncsetting.FieldAutoSyncEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_sync_enabled", values[i])
			} else if value.Valid {
				_m.AutoSyncEnabled = value.Bool
			}
		case clientsyncsetting.FieldAutoSyncIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field auto_sync_interval_minutes", values[i])
			} else if value.Valid {
				_m.AutoSyncIntervalMinutes = int(value.Int64)
			}
		case clientsyncsetting.FieldSyncOnStartup:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sync_on_startup", values[i])
			} else if value.Valid {
				_m.SyncOnStartup = value.Bool
			}
		case clientsyncsetting.FieldLastAutoSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_auto_sync_at", values[i])
			} else if value.Valid {
				_m.LastAutoSyncAt = new(time.Time)
				*_m.LastAutoSyncAt = value.Time
			}
		case clientsyncsetting.FieldLastAutoSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_auto_sync_status", values[i])
			} else if value.Valid {
				_m.LastAutoSyncStatus = new(clientsyncsetting.LastAutoSyncStatus)
				*_m.LastAutoSyncStatus = clientsyncsetting.LastAutoSyncStatus(value.String)
			}
		case clientsyncsetting.FieldLastAutoSyncError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_auto_sync_error", values[i])
			} else if value.Valid {
				_m.LastAutoSyncError = new(string)
				*_m.LastAutoSyncError = value.String
			}
		case clientsyncsetting.FieldAutoUpdateEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_update_enabled", values[i])
			} else if value.Valid {
				_m.AutoUpdateEnabled = value.Bool
			}
		case clientsyncsetting.FieldAutoUpdateIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field auto_update_interval_minutes", values[i])
			} else if value.Valid {
				_m.AutoUpdateIntervalMinutes = int(value.Int64)
			}
		case clientsyncsetting.FieldLastAutoUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_auto_update_at", values[i])
			} else if value.Valid {
				_m.LastAutoUpdateAt = new(time.Time)
				*_m.LastAutoUpdateAt = value.Time
			}
		case clientsyncsetting.FieldLastAutoUpdateStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_auto_update_status", values[i])
			} else if value.Valid {
				_m.LastAutoUpdateStatus = new(clientsyncsetting.LastAutoUpdateStatus)
				*_m.LastAutoUpdateStatus = clientsyncsetting.LastAutoUpdateStatus(value.String)
			}
		case clientsyncsetting.FieldLastAutoUpdateError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_auto_update_error", values[i])
			} else if value.Valid {
				_m.LastAutoUpdateError = new(string)
				*_m.LastAutoUpdateError = value.String
			}
		case clientsyncsetting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case clientsyncsetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ClientSyncSetting.
// This includes values selected through modifiers, order, etc.
func (_m *ClientSyncSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ClientSyncSetting.
// Note that you need to call ClientSyncSetting.Unwrap() before calling this method if this ClientSyncSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ClientSyncSetting) Update() *ClientSyncSettingUpdateOne {
	return NewClientSyncSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ClientSyncSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ClientSyncSetting) Unwrap() *ClientSyncSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClientSyncSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ClientSyncSetting) String() string {
	var builder strings.Builder
	builder.WriteString("ClientSyncSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("auto_sync_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoSyncEnabled))
	builder.WriteString(", ")
	builder.WriteString("auto_sync_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoSyncIntervalMinutes))
	builder.WriteString(", ")
	builder.WriteString("sync_on_startup=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncOnStartup))
	builder.WriteString(", ")
	if v := _m.LastAutoSyncAt; v != nil {
		builder.WriteString("last_auto_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastAutoSyncStatus; v != nil {
		builder.WriteString("last_auto_sync_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastAutoSyncError; v != nil {
		builder.WriteString("last_auto_sync_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("auto_update_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoUpdateEnabled))
	builder.WriteString(", ")
	builder.WriteString("auto_update_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoUpdateIntervalMinutes))
	builder.WriteString(", ")
	if v := _m.LastAutoUpdateAt; v != nil {
		builder.WriteString("last_auto_update_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastAutoUpdateStatus; v != nil {
		builder.WriteString("last_auto_update_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastAutoUpdateError; v != nil {
		builder.WriteString("last_auto_update_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ClientSyncSettings is a parsable slice of ClientSyncSetting.
type ClientSyncSettings []*ClientSyncSetting
