// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/clientinstallhistory"
	"lazycat.community/appstore/ent/predicate"
)

// ClientInstallHistoryUpdate is the builder for updating ClientInstallHistory entities.
type ClientInstallHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *ClientInstallHistoryMutation
}

// Where appends a list predicates to the ClientInstallHistoryUpdate builder.
func (_u *ClientInstallHistoryUpdate) Where(ps ...predicate.ClientInstallHistory) *ClientInstallHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ClientInstallHistoryUpdate) SetUserID(v string) *ClientInstallHistoryUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableUserID(v *string) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ClientInstallHistoryUpdate) SetSourceID(v int) *ClientInstallHistoryUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableSourceID(v *int) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *ClientInstallHistoryUpdate) AddSourceID(v int) *ClientInstallHistoryUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *ClientInstallHistoryUpdate) ClearSourceID() *ClientInstallHistoryUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceAppID sets the "source_app_id" field.
func (_u *ClientInstallHistoryUpdate) SetSourceAppID(v int) *ClientInstallHistoryUpdate {
	_u.mutation.ResetSourceAppID()
	_u.mutation.SetSourceAppID(v)
	return _u
}

// SetNillableSourceAppID sets the "source_app_id" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableSourceAppID(v *int) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetSourceAppID(*v)
	}
	return _u
}

// AddSourceAppID adds value to the "source_app_id" field.
func (_u *ClientInstallHistoryUpdate) AddSourceAppID(v int) *ClientInstallHistoryUpdate {
	_u.mutation.AddSourceAppID(v)
	return _u
}

// ClearSourceAppID clears the value of the "source_app_id" field.
func (_u *ClientInstallHistoryUpdate) ClearSourceAppID() *ClientInstallHistoryUpdate {
	_u.mutation.ClearSourceAppID()
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ClientInstallHistoryUpdate) SetSourceName(v string) *ClientInstallHistoryUpdate {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableSourceName(v *string) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *ClientInstallHistoryUpdate) SetPackageID(v string) *ClientInstallHistoryUpdate {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillablePackageID(v *string) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetAppName sets the "app_name" field.
func (_u *ClientInstallHistoryUpdate) SetAppName(v string) *ClientInstallHistoryUpdate {
	_u.mutation.SetAppName(v)
	return _u
}

// SetNillableAppName sets the "app_name" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableAppName(v *string) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetAppName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ClientInstallHistoryUpdate) SetVersion(v string) *ClientInstallHistoryUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableVersion(v *string) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *ClientInstallHistoryUpdate) SetResult(v clientinstallhistory.Result) *ClientInstallHistoryUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableResult(v *clientinstallhistory.Result) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetDownloadURL sets the "download_url" field.
func (_u *ClientInstallHistoryUpdate) SetDownloadURL(v string) *ClientInstallHistoryUpdate {
	_u.mutation.SetDownloadURL(v)
	return _u
}

// SetNillableDownloadURL sets the "download_url" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableDownloadURL(v *string) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetDownloadURL(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ClientInstallHistoryUpdate) SetSha256(v string) *ClientInstallHistoryUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableSha256(v *string) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *ClientInstallHistoryUpdate) SetError(v string) *ClientInstallHistoryUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableError(v *string) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ClientInstallHistoryUpdate) SetCreatedAt(v time.Time) *ClientInstallHistoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdate) SetNillableCreatedAt(v *time.Time) *ClientInstallHistoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ClientInstallHistoryMutation object of the builder.
func (_u *ClientInstallHistoryUpdate) Mutation() *ClientInstallHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClientInstallHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientInstallHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClientInstallHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientInstallHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientInstallHistoryUpdate) check() error {
	if v, ok := _u.mutation.PackageID(); ok {
		if err := clientinstallhistory.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "ClientInstallHistory.package_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppName(); ok {
		if err := clientinstallhistory.AppNameValidator(v); err != nil {
			return &ValidationError{Name: "app_name", err: fmt.Errorf(`ent: validator failed for field "ClientInstallHistory.app_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := clientinstallhistory.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "ClientInstallHistory.result": %w`, err)}
		}
	}
	return nil
}

func (_u *ClientInstallHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientinstallhistory.Table, clientinstallhistory.Columns, sqlgraph.NewFieldSpec(clientinstallhistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(clientinstallhistory.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(clientinstallhistory.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(clientinstallhistory.FieldSourceID, field.TypeInt, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(clientinstallhistory.FieldSourceID, field.TypeInt)
	}
	if value, ok := _u.mutation.SourceAppID(); ok {
		_spec.SetField(clientinstallhistory.FieldSourceAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceAppID(); ok {
		_spec.AddField(clientinstallhistory.FieldSourceAppID, field.TypeInt, value)
	}
	if _u.mutation.SourceAppIDCleared() {
		_spec.ClearField(clientinstallhistory.FieldSourceAppID, field.TypeInt)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(clientinstallhistory.FieldSourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(clientinstallhistory.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppName(); ok {
		_spec.SetField(clientinstallhistory.FieldAppName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(clientinstallhistory.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(clientinstallhistory.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DownloadURL(); ok {
		_spec.SetField(clientinstallhistory.FieldDownloadURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(clientinstallhistory.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(clientinstallhistory.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(clientinstallhistory.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientinstallhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClientInstallHistoryUpdateOne is the builder for updating a single ClientInstallHistory entity.
type ClientInstallHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClientInstallHistoryMutation
}

// SetUserID sets the "user_id" field.
func (_u *ClientInstallHistoryUpdateOne) SetUserID(v string) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableUserID(v *string) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ClientInstallHistoryUpdateOne) SetSourceID(v int) *ClientInstallHistoryUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableSourceID(v *int) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *ClientInstallHistoryUpdateOne) AddSourceID(v int) *ClientInstallHistoryUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *ClientInstallHistoryUpdateOne) ClearSourceID() *ClientInstallHistoryUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceAppID sets the "source_app_id" field.
func (_u *ClientInstallHistoryUpdateOne) SetSourceAppID(v int) *ClientInstallHistoryUpdateOne {
	_u.mutation.ResetSourceAppID()
	_u.mutation.SetSourceAppID(v)
	return _u
}

// SetNillableSourceAppID sets the "source_app_id" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableSourceAppID(v *int) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetSourceAppID(*v)
	}
	return _u
}

// AddSourceAppID adds value to the "source_app_id" field.
func (_u *ClientInstallHistoryUpdateOne) AddSourceAppID(v int) *ClientInstallHistoryUpdateOne {
	_u.mutation.AddSourceAppID(v)
	return _u
}

// ClearSourceAppID clears the value of the "source_app_id" field.
func (_u *ClientInstallHistoryUpdateOne) ClearSourceAppID() *ClientInstallHistoryUpdateOne {
	_u.mutation.ClearSourceAppID()
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ClientInstallHistoryUpdateOne) SetSourceName(v string) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableSourceName(v *string) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *ClientInstallHistoryUpdateOne) SetPackageID(v string) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillablePackageID(v *string) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetAppName sets the "app_name" field.
func (_u *ClientInstallHistoryUpdateOne) SetAppName(v string) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetAppName(v)
	return _u
}

// SetNillableAppName sets the "app_name" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableAppName(v *string) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetAppName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ClientInstallHistoryUpdateOne) SetVersion(v string) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableVersion(v *string) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *ClientInstallHistoryUpdateOne) SetResult(v clientinstallhistory.Result) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableResult(v *clientinstallhistory.Result) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetDownloadURL sets the "download_url" field.
func (_u *ClientInstallHistoryUpdateOne) SetDownloadURL(v string) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetDownloadURL(v)
	return _u
}

// SetNillableDownloadURL sets the "download_url" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableDownloadURL(v *string) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetDownloadURL(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ClientInstallHistoryUpdateOne) SetSha256(v string) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableSha256(v *string) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *ClientInstallHistoryUpdateOne) SetError(v string) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableError(v *string) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ClientInstallHistoryUpdateOne) SetCreatedAt(v time.Time) *ClientInstallHistoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ClientInstallHistoryUpdateOne) SetNillableCreatedAt(v *time.Time) *ClientInstallHistoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ClientInstallHistoryMutation object of the builder.
func (_u *ClientInstallHistoryUpdateOne) Mutation() *ClientInstallHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the ClientInstallHistoryUpdate builder.
func (_u *ClientInstallHistoryUpdateOne) Where(ps ...predicate.ClientInstallHistory) *ClientInstallHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClientInstallHistoryUpdateOne) Select(field string, fields ...string) *ClientInstallHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClientInstallHistory entity.
func (_u *ClientInstallHistoryUpdateOne) Save(ctx context.Context) (*ClientInstallHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientInstallHistoryUpdateOne) SaveX(ctx context.Context) *ClientInstallHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClientInstallHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientInstallHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientInstallHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.PackageID(); ok {
		if err := clientinstallhistory.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "ClientInstallHistory.package_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppName(); ok {
		if err := clientinstallhistory.AppNameValidator(v); err != nil {
			return &ValidationError{Name: "app_name", err: fmt.Errorf(`ent: validator failed for field "ClientInstallHistory.app_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := clientinstallhistory.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "ClientInstallHistory.result": %w`, err)}
		}
	}
	return nil
}

func (_u *ClientInstallHistoryUpdateOne) sqlSave(ctx context.Context) (_node *ClientInstallHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientinstallhistory.Table, clientinstallhistory.Columns, sqlgraph.NewFieldSpec(clientinstallhistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClientInstallHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clientinstallhistory.FieldID)
		for _, f := range fields {
			if !clientinstallhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clientinstallhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(clientinstallhistory.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(clientinstallhistory.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(clientinstallhistory.FieldSourceID, field.TypeInt, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(clientinstallhistory.FieldSourceID, field.TypeInt)
	}
	if value, ok := _u.mutation.SourceAppID(); ok {
		_spec.SetField(clientinstallhistory.FieldSourceAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceAppID(); ok {
		_spec.AddField(clientinstallhistory.FieldSourceAppID, field.TypeInt, value)
	}
	if _u.mutation.SourceAppIDCleared() {
		_spec.ClearField(clientinstallhistory.FieldSourceAppID, field.TypeInt)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(clientinstallhistory.FieldSourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(clientinstallhistory.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppName(); ok {
		_spec.SetField(clientinstallhistory.FieldAppName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(clientinstallhistory.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(clientinstallhistory.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DownloadURL(); ok {
		_spec.SetField(clientinstallhistory.FieldDownloadURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(clientinstallhistory.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(clientinstallhistory.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(clientinstallhistory.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &ClientInstallHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientinstallhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
