// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/clientsource"
	"lazycat.community/appstore/ent/clientsourceapp"
	"lazycat.community/appstore/ent/predicate"
)

// ClientSourceAppUpdate is the builder for updating ClientSourceApp entities.
type ClientSourceAppUpdate struct {
	config
	hooks    []Hook
	mutation *ClientSourceAppMutation
}

// Where appends a list predicates to the ClientSourceAppUpdate builder.
func (_u *ClientSourceAppUpdate) Where(ps ...predicate.ClientSourceApp) *ClientSourceAppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ClientSourceAppUpdate) SetSourceID(v int) *ClientSourceAppUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableSourceID(v *int) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ClientSourceAppUpdate) SetExternalID(v string) *ClientSourceAppUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableExternalID(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *ClientSourceAppUpdate) SetPackageID(v string) *ClientSourceAppUpdate {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillablePackageID(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ClientSourceAppUpdate) SetName(v string) *ClientSourceAppUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableName(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ClientSourceAppUpdate) SetSlug(v string) *ClientSourceAppUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableSlug(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ClientSourceAppUpdate) SetSummary(v string) *ClientSourceAppUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableSummary(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ClientSourceAppUpdate) SetCategory(v string) *ClientSourceAppUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableCategory(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetCategoryI18nJSON sets the "category_i18n_json" field.
func (_u *ClientSourceAppUpdate) SetCategoryI18nJSON(v string) *ClientSourceAppUpdate {
	_u.mutation.SetCategoryI18nJSON(v)
	return _u
}

// SetNillableCategoryI18nJSON sets the "category_i18n_json" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableCategoryI18nJSON(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetCategoryI18nJSON(*v)
	}
	return _u
}

// SetIconURL sets the "icon_url" field.
func (_u *ClientSourceAppUpdate) SetIconURL(v string) *ClientSourceAppUpdate {
	_u.mutation.SetIconURL(v)
	return _u
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableIconURL(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetIconURL(*v)
	}
	return _u
}

// SetInstallProtected sets the "install_protected" field.
func (_u *ClientSourceAppUpdate) SetInstallProtected(v bool) *ClientSourceAppUpdate {
	_u.mutation.SetInstallProtected(v)
	return _u
}

// SetNillableInstallProtected sets the "install_protected" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableInstallProtected(v *bool) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetInstallProtected(*v)
	}
	return _u
}

// SetOutdatedMarks sets the "outdated_marks" field.
func (_u *ClientSourceAppUpdate) SetOutdatedMarks(v int) *ClientSourceAppUpdate {
	_u.mutation.ResetOutdatedMarks()
	_u.mutation.SetOutdatedMarks(v)
	return _u
}

// SetNillableOutdatedMarks sets the "outdated_marks" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableOutdatedMarks(v *int) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetOutdatedMarks(*v)
	}
	return _u
}

// AddOutdatedMarks adds value to the "outdated_marks" field.
func (_u *ClientSourceAppUpdate) AddOutdatedMarks(v int) *ClientSourceAppUpdate {
	_u.mutation.AddOutdatedMarks(v)
	return _u
}

// SetScreenshotsJSON sets the "screenshots_json" field.
func (_u *ClientSourceAppUpdate) SetScreenshotsJSON(v string) *ClientSourceAppUpdate {
	_u.mutation.SetScreenshotsJSON(v)
	return _u
}

// SetNillableScreenshotsJSON sets the "screenshots_json" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableScreenshotsJSON(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetScreenshotsJSON(*v)
	}
	return _u
}

// SetLatestVersionJSON sets the "latest_version_json" field.
func (_u *ClientSourceAppUpdate) SetLatestVersionJSON(v string) *ClientSourceAppUpdate {
	_u.mutation.SetLatestVersionJSON(v)
	return _u
}

// SetNillableLatestVersionJSON sets the "latest_version_json" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableLatestVersionJSON(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetLatestVersionJSON(*v)
	}
	return _u
}

// SetVersionsJSON sets the "versions_json" field.
func (_u *ClientSourceAppUpdate) SetVersionsJSON(v string) *ClientSourceAppUpdate {
	_u.mutation.SetVersionsJSON(v)
	return _u
}

// SetNillableVersionsJSON sets the "versions_json" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableVersionsJSON(v *string) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetVersionsJSON(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ClientSourceAppUpdate) SetCreatedAt(v time.Time) *ClientSourceAppUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ClientSourceAppUpdate) SetNillableCreatedAt(v *time.Time) *ClientSourceAppUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClientSourceAppUpdate) SetUpdatedAt(v time.Time) *ClientSourceAppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSource sets the "source" edge to the ClientSource entity.
func (_u *ClientSourceAppUpdate) SetSource(v *ClientSource) *ClientSourceAppUpdate {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the ClientSourceAppMutation object of the builder.
func (_u *ClientSourceAppUpdate) Mutation() *ClientSourceAppMutation {
	return _u.mutation
}

// ClearSource clears the "source" edge to the ClientSource entity.
func (_u *ClientSourceAppUpdate) ClearSource() *ClientSourceAppUpdate {
	_u.mutation.ClearSource()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClientSourceAppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientSourceAppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClientSourceAppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientSourceAppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClientSourceAppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := clientsourceapp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientSourceAppUpdate) check() error {
	if v, ok := _u.mutation.PackageID(); ok {
		if err := clientsourceapp.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "ClientSourceApp.package_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := clientsourceapp.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientSourceApp.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := clientsourceapp.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ClientSourceApp.slug": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClientSourceApp.source"`)
	}
	return nil
}

func (_u *ClientSourceAppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientsourceapp.Table, clientsourceapp.Columns, sqlgraph.NewFieldSpec(clientsourceapp.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(clientsourceapp.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(clientsourceapp.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(clientsourceapp.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(clientsourceapp.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(clientsourceapp.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(clientsourceapp.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoryI18nJSON(); ok {
		_spec.SetField(clientsourceapp.FieldCategoryI18nJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconURL(); ok {
		_spec.SetField(clientsourceapp.FieldIconURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallProtected(); ok {
		_spec.SetField(clientsourceapp.FieldInstallProtected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutdatedMarks(); ok {
		_spec.SetField(clientsourceapp.FieldOutdatedMarks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutdatedMarks(); ok {
		_spec.AddField(clientsourceapp.FieldOutdatedMarks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScreenshotsJSON(); ok {
		_spec.SetField(clientsourceapp.FieldScreenshotsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatestVersionJSON(); ok {
		_spec.SetField(clientsourceapp.FieldLatestVersionJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.VersionsJSON(); ok {
		_spec.SetField(clientsourceapp.FieldVersionsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(clientsourceapp.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(clientsourceapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clientsourceapp.SourceTable,
			Columns: []string{clientsourceapp.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientsource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clientsourceapp.SourceTable,
			Columns: []string{clientsourceapp.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientsource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientsourceapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClientSourceAppUpdateOne is the builder for updating a single ClientSourceApp entity.
type ClientSourceAppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClientSourceAppMutation
}

// SetSourceID sets the "source_id" field.
func (_u *ClientSourceAppUpdateOne) SetSourceID(v int) *ClientSourceAppUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableSourceID(v *int) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ClientSourceAppUpdateOne) SetExternalID(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableExternalID(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *ClientSourceAppUpdateOne) SetPackageID(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillablePackageID(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ClientSourceAppUpdateOne) SetName(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableName(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ClientSourceAppUpdateOne) SetSlug(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableSlug(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ClientSourceAppUpdateOne) SetSummary(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableSummary(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ClientSourceAppUpdateOne) SetCategory(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableCategory(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetCategoryI18nJSON sets the "category_i18n_json" field.
func (_u *ClientSourceAppUpdateOne) SetCategoryI18nJSON(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetCategoryI18nJSON(v)
	return _u
}

// SetNillableCategoryI18nJSON sets the "category_i18n_json" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableCategoryI18nJSON(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetCategoryI18nJSON(*v)
	}
	return _u
}

// SetIconURL sets the "icon_url" field.
func (_u *ClientSourceAppUpdateOne) SetIconURL(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetIconURL(v)
	return _u
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableIconURL(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetIconURL(*v)
	}
	return _u
}

// SetInstallProtected sets the "install_protected" field.
func (_u *ClientSourceAppUpdateOne) SetInstallProtected(v bool) *ClientSourceAppUpdateOne {
	_u.mutation.SetInstallProtected(v)
	return _u
}

// SetNillableInstallProtected sets the "install_protected" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableInstallProtected(v *bool) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetInstallProtected(*v)
	}
	return _u
}

// SetOutdatedMarks sets the "outdated_marks" field.
func (_u *ClientSourceAppUpdateOne) SetOutdatedMarks(v int) *ClientSourceAppUpdateOne {
	_u.mutation.ResetOutdatedMarks()
	_u.mutation.SetOutdatedMarks(v)
	return _u
}

// SetNillableOutdatedMarks sets the "outdated_marks" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableOutdatedMarks(v *int) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetOutdatedMarks(*v)
	}
	return _u
}

// AddOutdatedMarks adds value to the "outdated_marks" field.
func (_u *ClientSourceAppUpdateOne) AddOutdatedMarks(v int) *ClientSourceAppUpdateOne {
	_u.mutation.AddOutdatedMarks(v)
	return _u
}

// SetScreenshotsJSON sets the "screenshots_json" field.
func (_u *ClientSourceAppUpdateOne) SetScreenshotsJSON(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetScreenshotsJSON(v)
	return _u
}

// SetNillableScreenshotsJSON sets the "screenshots_json" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableScreenshotsJSON(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetScreenshotsJSON(*v)
	}
	return _u
}

// SetLatestVersionJSON sets the "latest_version_json" field.
func (_u *ClientSourceAppUpdateOne) SetLatestVersionJSON(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetLatestVersionJSON(v)
	return _u
}

// SetNillableLatestVersionJSON sets the "latest_version_json" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableLatestVersionJSON(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetLatestVersionJSON(*v)
	}
	return _u
}

// SetVersionsJSON sets the "versions_json" field.
func (_u *ClientSourceAppUpdateOne) SetVersionsJSON(v string) *ClientSourceAppUpdateOne {
	_u.mutation.SetVersionsJSON(v)
	return _u
}

// SetNillableVersionsJSON sets the "versions_json" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableVersionsJSON(v *string) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetVersionsJSON(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ClientSourceAppUpdateOne) SetCreatedAt(v time.Time) *ClientSourceAppUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ClientSourceAppUpdateOne) SetNillableCreatedAt(v *time.Time) *ClientSourceAppUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClientSourceAppUpdateOne) SetUpdatedAt(v time.Time) *ClientSourceAppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSource sets the "source" edge to the ClientSource entity.
func (_u *ClientSourceAppUpdateOne) SetSource(v *ClientSource) *ClientSourceAppUpdateOne {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the ClientSourceAppMutation object of the builder.
func (_u *ClientSourceAppUpdateOne) Mutation() *ClientSourceAppMutation {
	return _u.mutation
}

// ClearSource clears the "source" edge to the ClientSource entity.
func (_u *ClientSourceAppUpdateOne) ClearSource() *ClientSourceAppUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// Where appends a list predicates to the ClientSourceAppUpdate builder.
func (_u *ClientSourceAppUpdateOne) Where(ps ...predicate.ClientSourceApp) *ClientSourceAppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClientSourceAppUpdateOne) Select(field string, fields ...string) *ClientSourceAppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClientSourceApp entity.
func (_u *ClientSourceAppUpdateOne) Save(ctx context.Context) (*ClientSourceApp, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientSourceAppUpdateOne) SaveX(ctx context.Context) *ClientSourceApp {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClientSourceAppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientSourceAppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClientSourceAppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := clientsourceapp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientSourceAppUpdateOne) check() error {
	if v, ok := _u.mutation.PackageID(); ok {
		if err := clientsourceapp.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "ClientSourceApp.package_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := clientsourceapp.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientSourceApp.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := clientsourceapp.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ClientSourceApp.slug": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClientSourceApp.source"`)
	}
	return nil
}

func (_u *ClientSourceAppUpdateOne) sqlSave(ctx context.Context) (_node *ClientSourceApp, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientsourceapp.Table, clientsourceapp.Columns, sqlgraph.NewFieldSpec(clientsourceapp.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClientSourceApp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clientsourceapp.FieldID)
		for _, f := range fields {
			if !clientsourceapp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clientsourceapp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(clientsourceapp.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(clientsourceapp.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(clientsourceapp.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(clientsourceapp.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(clientsourceapp.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(clientsourceapp.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoryI18nJSON(); ok {
		_spec.SetField(clientsourceapp.FieldCategoryI18nJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconURL(); ok {
		_spec.SetField(clientsourceapp.FieldIconURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallProtected(); ok {
		_spec.SetField(clientsourceapp.FieldInstallProtected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutdatedMarks(); ok {
		_spec.SetField(clientsourceapp.FieldOutdatedMarks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutdatedMarks(); ok {
		_spec.AddField(clientsourceapp.FieldOutdatedMarks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScreenshotsJSON(); ok {
		_spec.SetField(clientsourceapp.FieldScreenshotsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatestVersionJSON(); ok {
		_spec.SetField(clientsourceapp.FieldLatestVersionJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.VersionsJSON(); ok {
		_spec.SetField(clientsourceapp.FieldVersionsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(clientsourceapp.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(clientsourceapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clientsourceapp.SourceTable,
			Columns: []string{clientsourceapp.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientsource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clientsourceapp.SourceTable,
			Columns: []string{clientsourceapp.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientsource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ClientSourceApp{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientsourceapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
