// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/clientinstallhistory"
	"lazycat.community/appstore/ent/predicate"
)

// ClientInstallHistoryDelete is the builder for deleting a ClientInstallHistory entity.
type ClientInstallHistoryDelete struct {
	config
	hooks    []Hook
	mutation *ClientInstallHistoryMutation
}

// Where appends a list predicates to the ClientInstallHistoryDelete builder.
func (_d *ClientInstallHistoryDelete) Where(ps ...predicate.ClientInstallHistory) *ClientInstallHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ClientInstallHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClientInstallHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ClientInstallHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(clientinstallhistory.Table, sqlgraph.NewFieldSpec(clientinstallhistory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ClientInstallHistoryDeleteOne is the builder for deleting a single ClientInstallHistory entity.
type ClientInstallHistoryDeleteOne struct {
	_d *ClientInstallHistoryDelete
}

// Where appends a list predicates to the ClientInstallHistoryDelete builder.
func (_d *ClientInstallHistoryDeleteOne) Where(ps ...predicate.ClientInstallHistory) *ClientInstallHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ClientInstallHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clientinstallhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClientInstallHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
