// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/commentnotification"
	"lazycat.community/appstore/ent/predicate"
)

// CommentNotificationUpdate is the builder for updating CommentNotification entities.
type CommentNotificationUpdate struct {
	config
	hooks    []Hook
	mutation *CommentNotificationMutation
}

// Where appends a list predicates to the CommentNotificationUpdate builder.
func (_u *CommentNotificationUpdate) Where(ps ...predicate.CommentNotification) *CommentNotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *CommentNotificationUpdate) SetOwnerID(v int) *CommentNotificationUpdate {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *CommentNotificationUpdate) SetNillableOwnerID(v *int) *CommentNotificationUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *CommentNotificationUpdate) AddOwnerID(v int) *CommentNotificationUpdate {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *CommentNotificationUpdate) SetAppID(v int) *CommentNotificationUpdate {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *CommentNotificationUpdate) SetNillableAppID(v *int) *CommentNotificationUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *CommentNotificationUpdate) AddAppID(v int) *CommentNotificationUpdate {
	_u.mutation.AddAppID(v)
	return _u
}

// SetCommentID sets the "comment_id" field.
func (_u *CommentNotificationUpdate) SetCommentID(v int) *CommentNotificationUpdate {
	_u.mutation.ResetCommentID()
	_u.mutation.SetCommentID(v)
	return _u
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (_u *CommentNotificationUpdate) SetNillableCommentID(v *int) *CommentNotificationUpdate {
	if v != nil {
		_u.SetCommentID(*v)
	}
	return _u
}

// AddCommentID adds value to the "comment_id" field.
func (_u *CommentNotificationUpdate) AddCommentID(v int) *CommentNotificationUpdate {
	_u.mutation.AddCommentID(v)
	return _u
}

// SetAppName sets the "app_name" field.
func (_u *CommentNotificationUpdate) SetAppName(v string) *CommentNotificationUpdate {
	_u.mutation.SetAppName(v)
	return _u
}

// SetNillableAppName sets the "app_name" field if the given value is not nil.
func (_u *CommentNotificationUpdate) SetNillableAppName(v *string) *CommentNotificationUpdate {
	if v != nil {
		_u.SetAppName(*v)
	}
	return _u
}

// SetActorName sets the "actor_name" field.
func (_u *CommentNotificationUpdate) SetActorName(v string) *CommentNotificationUpdate {
	_u.mutation.SetActorName(v)
	return _u
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_u *CommentNotificationUpdate) SetNillableActorName(v *string) *CommentNotificationUpdate {
	if v != nil {
		_u.SetActorName(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *CommentNotificationUpdate) SetBody(v string) *CommentNotificationUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *CommentNotificationUpdate) SetNillableBody(v *string) *CommentNotificationUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetRead sets the "read" field.
func (_u *CommentNotificationUpdate) SetRead(v bool) *CommentNotificationUpdate {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *CommentNotificationUpdate) SetNillableRead(v *bool) *CommentNotificationUpdate {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CommentNotificationUpdate) SetCreatedAt(v time.Time) *CommentNotificationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CommentNotificationUpdate) SetNillableCreatedAt(v *time.Time) *CommentNotificationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the CommentNotificationMutation object of the builder.
func (_u *CommentNotificationUpdate) Mutation() *CommentNotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommentNotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentNotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommentNotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentNotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CommentNotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(commentnotification.Table, commentnotification.Columns, sqlgraph.NewFieldSpec(commentnotification.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(commentnotification.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(commentnotification.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(commentnotification.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(commentnotification.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommentID(); ok {
		_spec.SetField(commentnotification.FieldCommentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentID(); ok {
		_spec.AddField(commentnotification.FieldCommentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AppName(); ok {
		_spec.SetField(commentnotification.FieldAppName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorName(); ok {
		_spec.SetField(commentnotification.FieldActorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(commentnotification.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(commentnotification.FieldRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(commentnotification.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commentnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommentNotificationUpdateOne is the builder for updating a single CommentNotification entity.
type CommentNotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentNotificationMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *CommentNotificationUpdateOne) SetOwnerID(v int) *CommentNotificationUpdateOne {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *CommentNotificationUpdateOne) SetNillableOwnerID(v *int) *CommentNotificationUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *CommentNotificationUpdateOne) AddOwnerID(v int) *CommentNotificationUpdateOne {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *CommentNotificationUpdateOne) SetAppID(v int) *CommentNotificationUpdateOne {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *CommentNotificationUpdateOne) SetNillableAppID(v *int) *CommentNotificationUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *CommentNotificationUpdateOne) AddAppID(v int) *CommentNotificationUpdateOne {
	_u.mutation.AddAppID(v)
	return _u
}

// SetCommentID sets the "comment_id" field.
func (_u *CommentNotificationUpdateOne) SetCommentID(v int) *CommentNotificationUpdateOne {
	_u.mutation.ResetCommentID()
	_u.mutation.SetCommentID(v)
	return _u
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (_u *CommentNotificationUpdateOne) SetNillableCommentID(v *int) *CommentNotificationUpdateOne {
	if v != nil {
		_u.SetCommentID(*v)
	}
	return _u
}

// AddCommentID adds value to the "comment_id" field.
func (_u *CommentNotificationUpdateOne) AddCommentID(v int) *CommentNotificationUpdateOne {
	_u.mutation.AddCommentID(v)
	return _u
}

// SetAppName sets the "app_name" field.
func (_u *CommentNotificationUpdateOne) SetAppName(v string) *CommentNotificationUpdateOne {
	_u.mutation.SetAppName(v)
	return _u
}

// SetNillableAppName sets the "app_name" field if the given value is not nil.
func (_u *CommentNotificationUpdateOne) SetNillableAppName(v *string) *CommentNotificationUpdateOne {
	if v != nil {
		_u.SetAppName(*v)
	}
	return _u
}

// SetActorName sets the "actor_name" field.
func (_u *CommentNotificationUpdateOne) SetActorName(v string) *CommentNotificationUpdateOne {
	_u.mutation.SetActorName(v)
	return _u
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_u *CommentNotificationUpdateOne) SetNillableActorName(v *string) *CommentNotificationUpdateOne {
	if v != nil {
		_u.SetActorName(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *CommentNotificationUpdateOne) SetBody(v string) *CommentNotificationUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *CommentNotificationUpdateOne) SetNillableBody(v *string) *CommentNotificationUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetRead sets the "read" field.
func (_u *CommentNotificationUpdateOne) SetRead(v bool) *CommentNotificationUpdateOne {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *CommentNotificationUpdateOne) SetNillableRead(v *bool) *CommentNotificationUpdateOne {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CommentNotificationUpdateOne) SetCreatedAt(v time.Time) *CommentNotificationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CommentNotificationUpdateOne) SetNillableCreatedAt(v *time.Time) *CommentNotificationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the CommentNotificationMutation object of the builder.
func (_u *CommentNotificationUpdateOne) Mutation() *CommentNotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommentNotificationUpdate builder.
func (_u *CommentNotificationUpdateOne) Where(ps ...predicate.CommentNotification) *CommentNotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommentNotificationUpdateOne) Select(field string, fields ...string) *CommentNotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CommentNotification entity.
func (_u *CommentNotificationUpdateOne) Save(ctx context.Context) (*CommentNotification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentNotificationUpdateOne) SaveX(ctx context.Context) *CommentNotification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommentNotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentNotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CommentNotificationUpdateOne) sqlSave(ctx context.Context) (_node *CommentNotification, err error) {
	_spec := sqlgraph.NewUpdateSpec(commentnotification.Table, commentnotification.Columns, sqlgraph.NewFieldSpec(commentnotification.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommentNotification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commentnotification.FieldID)
		for _, f := range fields {
			if !commentnotification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commentnotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(commentnotification.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(commentnotification.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(commentnotification.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(commentnotification.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommentID(); ok {
		_spec.SetField(commentnotification.FieldCommentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentID(); ok {
		_spec.AddField(commentnotification.FieldCommentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AppName(); ok {
		_spec.SetField(commentnotification.FieldAppName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorName(); ok {
		_spec.SetField(commentnotification.FieldActorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(commentnotification.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(commentnotification.FieldRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(commentnotification.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &CommentNotification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commentnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
