// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"lazycat.community/appstore/ent/app"
	"lazycat.community/appstore/ent/githublpkupdatepolicy"
)

// GitHubLPKUpdatePolicy is the model entity for the GitHubLPKUpdatePolicy schema.
type GitHubLPKUpdatePolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID int `json:"app_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// IntervalMinutes holds the value of the "interval_minutes" field.
	IntervalMinutes int `json:"interval_minutes,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	// LastSuccessAt holds the value of the "last_success_at" field.
	LastSuccessAt *time.Time `json:"last_success_at,omitempty"`
	// NextCheckAt holds the value of the "next_check_at" field.
	NextCheckAt *time.Time `json:"next_check_at,omitempty"`
	// LastVersion holds the value of the "last_version" field.
	LastVersion string `json:"last_version,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GitHubLPKUpdatePolicyQuery when eager-loading is set.
	Edges        GitHubLPKUpdatePolicyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GitHubLPKUpdatePolicyEdges holds the relations/edges for other nodes in the graph.
type GitHubLPKUpdatePolicyEdges struct {
	// App holds the value of the app edge.
	App *App `json:"app,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GitHubLPKUpdatePolicyEdges) AppOrErr() (*App, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: app.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GitHubLPKUpdatePolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case githublpkupdatepolicy.FieldEnabled:
			values[i] = new(sql.NullBool)
		case githublpkupdatepolicy.FieldID, githublpkupdatepolicy.FieldAppID, githublpkupdatepolicy.FieldIntervalMinutes:
			values[i] = new(sql.NullInt64)
		case githublpkupdatepolicy.FieldLastVersion, githublpkupdatepolicy.FieldLastError:
			values[i] = new(sql.NullString)
		case githublpkupdatepolicy.FieldLastCheckedAt, githublpkupdatepolicy.FieldLastSuccessAt, githublpkupdatepolicy.FieldNextCheckAt, githublpkupdatepolicy.FieldCreatedAt, githublpkupdatepolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GitHubLPKUpdatePolicy fields.
func (_m *GitHubLPKUpdatePolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case githublpkupdatepolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case githublpkupdatepolicy.FieldAppID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = int(value.Int64)
			}
		case githublpkupdatepolicy.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case githublpkupdatepolicy.FieldIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval_minutes", values[i])
			} else if value.Valid {
				_m.IntervalMinutes = int(value.Int64)
			}
		case githublpkupdatepolicy.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		case githublpkupdatepolicy.FieldLastSuccessAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_success_at", values[i])
			} else if value.Valid {
				_m.LastSuccessAt = new(time.Time)
				*_m.LastSuccessAt = value.Time
			}
		case githublpkupdatepolicy.FieldNextCheckAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_check_at", values[i])
			} else if value.Valid {
				_m.NextCheckAt = new(time.Time)
				*_m.NextCheckAt = value.Time
			}
		case githublpkupdatepolicy.FieldLastVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_version", values[i])
			} else if value.Valid {
				_m.LastVersion = value.String
			}
		case githublpkupdatepolicy.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case githublpkupdatepolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case githublpkupdatepolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GitHubLPKUpdatePolicy.
// This includes values selected through modifiers, order, etc.
func (_m *GitHubLPKUpdatePolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryApp queries the "app" edge of the GitHubLPKUpdatePolicy entity.
func (_m *GitHubLPKUpdatePolicy) QueryApp() *AppQuery {
	return NewGitHubLPKUpdatePolicyClient(_m.config).QueryApp(_m)
}

// Update returns a builder for updating this GitHubLPKUpdatePolicy.
// Note that you need to call GitHubLPKUpdatePolicy.Unwrap() before calling this method if this GitHubLPKUpdatePolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GitHubLPKUpdatePolicy) Update() *GitHubLPKUpdatePolicyUpdateOne {
	return NewGitHubLPKUpdatePolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GitHubLPKUpdatePolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GitHubLPKUpdatePolicy) Unwrap() *GitHubLPKUpdatePolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GitHubLPKUpdatePolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GitHubLPKUpdatePolicy) String() string {
	var builder strings.Builder
	builder.WriteString("GitHubLPKUpdatePolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntervalMinutes))
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastSuccessAt; v != nil {
		builder.WriteString("last_success_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextCheckAt; v != nil {
		builder.WriteString("next_check_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_version=")
	builder.WriteString(_m.LastVersion)
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GitHubLPKUpdatePolicies is a parsable slice of GitHubLPKUpdatePolicy.
type GitHubLPKUpdatePolicies []*GitHubLPKUpdatePolicy
