// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/mcptoken"
)

// MCPTokenCreate is the builder for creating a MCPToken entity.
type MCPTokenCreate struct {
	config
	mutation *MCPTokenMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *MCPTokenCreate) SetUserID(v int) *MCPTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPrincipalType sets the "principal_type" field.
func (_c *MCPTokenCreate) SetPrincipalType(v mcptoken.PrincipalType) *MCPTokenCreate {
	_c.mutation.SetPrincipalType(v)
	return _c
}

// SetNillablePrincipalType sets the "principal_type" field if the given value is not nil.
func (_c *MCPTokenCreate) SetNillablePrincipalType(v *mcptoken.PrincipalType) *MCPTokenCreate {
	if v != nil {
		_c.SetPrincipalType(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *MCPTokenCreate) SetNote(v string) *MCPTokenCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *MCPTokenCreate) SetNillableNote(v *string) *MCPTokenCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetPrefix sets the "prefix" field.
func (_c *MCPTokenCreate) SetPrefix(v string) *MCPTokenCreate {
	_c.mutation.SetPrefix(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *MCPTokenCreate) SetTokenHash(v string) *MCPTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *MCPTokenCreate) SetExpiresAt(v time.Time) *MCPTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *MCPTokenCreate) SetNillableExpiresAt(v *time.Time) *MCPTokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *MCPTokenCreate) SetLastUsedAt(v time.Time) *MCPTokenCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *MCPTokenCreate) SetNillableLastUsedAt(v *time.Time) *MCPTokenCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MCPTokenCreate) SetCreatedAt(v time.Time) *MCPTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MCPTokenCreate) SetNillableCreatedAt(v *time.Time) *MCPTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the MCPTokenMutation object of the builder.
func (_c *MCPTokenCreate) Mutation() *MCPTokenMutation {
	return _c.mutation
}

// Save creates the MCPToken in the database.
func (_c *MCPTokenCreate) Save(ctx context.Context) (*MCPToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MCPTokenCreate) SaveX(ctx context.Context) *MCPToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MCPTokenCreate) defaults() {
	if _, ok := _c.mutation.PrincipalType(); !ok {
		v := mcptoken.DefaultPrincipalType
		_c.mutation.SetPrincipalType(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := mcptoken.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mcptoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MCPTokenCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MCPToken.user_id"`)}
	}
	if _, ok := _c.mutation.PrincipalType(); !ok {
		return &ValidationError{Name: "principal_type", err: errors.New(`ent: missing required field "MCPToken.principal_type"`)}
	}
	if v, ok := _c.mutation.PrincipalType(); ok {
		if err := mcptoken.PrincipalTypeValidator(v); err != nil {
			return &ValidationError{Name: "principal_type", err: fmt.Errorf(`ent: validator failed for field "MCPToken.principal_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "MCPToken.note"`)}
	}
	if _, ok := _c.mutation.Prefix(); !ok {
		return &ValidationError{Name: "prefix", err: errors.New(`ent: missing required field "MCPToken.prefix"`)}
	}
	if v, ok := _c.mutation.Prefix(); ok {
		if err := mcptoken.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "MCPToken.prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "MCPToken.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := mcptoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "MCPToken.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MCPToken.created_at"`)}
	}
	return nil
}

func (_c *MCPTokenCreate) sqlSave(ctx context.Context) (*MCPToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MCPTokenCreate) createSpec() (*MCPToken, *sqlgraph.CreateSpec) {
	var (
		_node = &MCPToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mcptoken.Table, sqlgraph.NewFieldSpec(mcptoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(mcptoken.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PrincipalType(); ok {
		_spec.SetField(mcptoken.FieldPrincipalType, field.TypeEnum, value)
		_node.PrincipalType = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(mcptoken.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.Prefix(); ok {
		_spec.SetField(mcptoken.FieldPrefix, field.TypeString, value)
		_node.Prefix = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(mcptoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(mcptoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(mcptoken.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mcptoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MCPTokenCreateBulk is the builder for creating many MCPToken entities in bulk.
type MCPTokenCreateBulk struct {
	config
	err      error
	builders []*MCPTokenCreate
}

// Save creates the MCPToken entities in the database.
func (_c *MCPTokenCreateBulk) Save(ctx context.Context) ([]*MCPToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MCPToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MCPTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MCPTokenCreateBulk) SaveX(ctx context.Context) []*MCPToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
