// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"lazycat.community/appstore/ent/predicate"
	"lazycat.community/appstore/ent/reviewrequest"
)

// ReviewRequestUpdate is the builder for updating ReviewRequest entities.
type ReviewRequestUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewRequestMutation
}

// Where appends a list predicates to the ReviewRequestUpdate builder.
func (_u *ReviewRequestUpdate) Where(ps ...predicate.ReviewRequest) *ReviewRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *ReviewRequestUpdate) SetKind(v reviewrequest.Kind) *ReviewRequestUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableKind(v *reviewrequest.Kind) *ReviewRequestUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReviewRequestUpdate) SetStatus(v reviewrequest.Status) *ReviewRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableStatus(v *reviewrequest.Status) *ReviewRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ReviewRequestUpdate) SetAppID(v int) *ReviewRequestUpdate {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableAppID(v *int) *ReviewRequestUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *ReviewRequestUpdate) AddAppID(v int) *ReviewRequestUpdate {
	_u.mutation.AddAppID(v)
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *ReviewRequestUpdate) ClearAppID() *ReviewRequestUpdate {
	_u.mutation.ClearAppID()
	return _u
}

// SetVersionID sets the "version_id" field.
func (_u *ReviewRequestUpdate) SetVersionID(v int) *ReviewRequestUpdate {
	_u.mutation.ResetVersionID()
	_u.mutation.SetVersionID(v)
	return _u
}

// SetNillableVersionID sets the "version_id" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableVersionID(v *int) *ReviewRequestUpdate {
	if v != nil {
		_u.SetVersionID(*v)
	}
	return _u
}

// AddVersionID adds value to the "version_id" field.
func (_u *ReviewRequestUpdate) AddVersionID(v int) *ReviewRequestUpdate {
	_u.mutation.AddVersionID(v)
	return _u
}

// ClearVersionID clears the value of the "version_id" field.
func (_u *ReviewRequestUpdate) ClearVersionID() *ReviewRequestUpdate {
	_u.mutation.ClearVersionID()
	return _u
}

// SetRequesterID sets the "requester_id" field.
func (_u *ReviewRequestUpdate) SetRequesterID(v int) *ReviewRequestUpdate {
	_u.mutation.ResetRequesterID()
	_u.mutation.SetRequesterID(v)
	return _u
}

// SetNillableRequesterID sets the "requester_id" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableRequesterID(v *int) *ReviewRequestUpdate {
	if v != nil {
		_u.SetRequesterID(*v)
	}
	return _u
}

// AddRequesterID adds value to the "requester_id" field.
func (_u *ReviewRequestUpdate) AddRequesterID(v int) *ReviewRequestUpdate {
	_u.mutation.AddRequesterID(v)
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *ReviewRequestUpdate) SetReviewerID(v int) *ReviewRequestUpdate {
	_u.mutation.ResetReviewerID()
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableReviewerID(v *int) *ReviewRequestUpdate {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// AddReviewerID adds value to the "reviewer_id" field.
func (_u *ReviewRequestUpdate) AddReviewerID(v int) *ReviewRequestUpdate {
	_u.mutation.AddReviewerID(v)
	return _u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (_u *ReviewRequestUpdate) ClearReviewerID() *ReviewRequestUpdate {
	_u.mutation.ClearReviewerID()
	return _u
}

// SetNote sets the "note" field.
func (_u *ReviewRequestUpdate) SetNote(v string) *ReviewRequestUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableNote(v *string) *ReviewRequestUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *ReviewRequestUpdate) SetReviewNote(v string) *ReviewRequestUpdate {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableReviewNote(v *string) *ReviewRequestUpdate {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ReviewRequestUpdate) SetReviewedAt(v time.Time) *ReviewRequestUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableReviewedAt(v *time.Time) *ReviewRequestUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *ReviewRequestUpdate) ClearReviewedAt() *ReviewRequestUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReviewRequestUpdate) SetCreatedAt(v time.Time) *ReviewRequestUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReviewRequestUpdate) SetNillableCreatedAt(v *time.Time) *ReviewRequestUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReviewRequestUpdate) SetUpdatedAt(v time.Time) *ReviewRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReviewRequestMutation object of the builder.
func (_u *ReviewRequestUpdate) Mutation() *ReviewRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReviewRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reviewrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewRequestUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := reviewrequest.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ReviewRequest.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := reviewrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReviewRequest.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReviewRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reviewrequest.Table, reviewrequest.Columns, sqlgraph.NewFieldSpec(reviewrequest.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(reviewrequest.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reviewrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(reviewrequest.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(reviewrequest.FieldAppID, field.TypeInt, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(reviewrequest.FieldAppID, field.TypeInt)
	}
	if value, ok := _u.mutation.VersionID(); ok {
		_spec.SetField(reviewrequest.FieldVersionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionID(); ok {
		_spec.AddField(reviewrequest.FieldVersionID, field.TypeInt, value)
	}
	if _u.mutation.VersionIDCleared() {
		_spec.ClearField(reviewrequest.FieldVersionID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequesterID(); ok {
		_spec.SetField(reviewrequest.FieldRequesterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequesterID(); ok {
		_spec.AddField(reviewrequest.FieldRequesterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(reviewrequest.FieldReviewerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewerID(); ok {
		_spec.AddField(reviewrequest.FieldReviewerID, field.TypeInt, value)
	}
	if _u.mutation.ReviewerIDCleared() {
		_spec.ClearField(reviewrequest.FieldReviewerID, field.TypeInt)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(reviewrequest.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(reviewrequest.FieldReviewNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(reviewrequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(reviewrequest.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(reviewrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reviewrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reviewrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewRequestUpdateOne is the builder for updating a single ReviewRequest entity.
type ReviewRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewRequestMutation
}

// SetKind sets the "kind" field.
func (_u *ReviewRequestUpdateOne) SetKind(v reviewrequest.Kind) *ReviewRequestUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableKind(v *reviewrequest.Kind) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReviewRequestUpdateOne) SetStatus(v reviewrequest.Status) *ReviewRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableStatus(v *reviewrequest.Status) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ReviewRequestUpdateOne) SetAppID(v int) *ReviewRequestUpdateOne {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableAppID(v *int) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *ReviewRequestUpdateOne) AddAppID(v int) *ReviewRequestUpdateOne {
	_u.mutation.AddAppID(v)
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *ReviewRequestUpdateOne) ClearAppID() *ReviewRequestUpdateOne {
	_u.mutation.ClearAppID()
	return _u
}

// SetVersionID sets the "version_id" field.
func (_u *ReviewRequestUpdateOne) SetVersionID(v int) *ReviewRequestUpdateOne {
	_u.mutation.ResetVersionID()
	_u.mutation.SetVersionID(v)
	return _u
}

// SetNillableVersionID sets the "version_id" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableVersionID(v *int) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetVersionID(*v)
	}
	return _u
}

// AddVersionID adds value to the "version_id" field.
func (_u *ReviewRequestUpdateOne) AddVersionID(v int) *ReviewRequestUpdateOne {
	_u.mutation.AddVersionID(v)
	return _u
}

// ClearVersionID clears the value of the "version_id" field.
func (_u *ReviewRequestUpdateOne) ClearVersionID() *ReviewRequestUpdateOne {
	_u.mutation.ClearVersionID()
	return _u
}

// SetRequesterID sets the "requester_id" field.
func (_u *ReviewRequestUpdateOne) SetRequesterID(v int) *ReviewRequestUpdateOne {
	_u.mutation.ResetRequesterID()
	_u.mutation.SetRequesterID(v)
	return _u
}

// SetNillableRequesterID sets the "requester_id" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableRequesterID(v *int) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetRequesterID(*v)
	}
	return _u
}

// AddRequesterID adds value to the "requester_id" field.
func (_u *ReviewRequestUpdateOne) AddRequesterID(v int) *ReviewRequestUpdateOne {
	_u.mutation.AddRequesterID(v)
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *ReviewRequestUpdateOne) SetReviewerID(v int) *ReviewRequestUpdateOne {
	_u.mutation.ResetReviewerID()
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableReviewerID(v *int) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// AddReviewerID adds value to the "reviewer_id" field.
func (_u *ReviewRequestUpdateOne) AddReviewerID(v int) *ReviewRequestUpdateOne {
	_u.mutation.AddReviewerID(v)
	return _u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (_u *ReviewRequestUpdateOne) ClearReviewerID() *ReviewRequestUpdateOne {
	_u.mutation.ClearReviewerID()
	return _u
}

// SetNote sets the "note" field.
func (_u *ReviewRequestUpdateOne) SetNote(v string) *ReviewRequestUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableNote(v *string) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *ReviewRequestUpdateOne) SetReviewNote(v string) *ReviewRequestUpdateOne {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableReviewNote(v *string) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ReviewRequestUpdateOne) SetReviewedAt(v time.Time) *ReviewRequestUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableReviewedAt(v *time.Time) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *ReviewRequestUpdateOne) ClearReviewedAt() *ReviewRequestUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReviewRequestUpdateOne) SetCreatedAt(v time.Time) *ReviewRequestUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReviewRequestUpdateOne) SetNillableCreatedAt(v *time.Time) *ReviewRequestUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReviewRequestUpdateOne) SetUpdatedAt(v time.Time) *ReviewRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReviewRequestMutation object of the builder.
func (_u *ReviewRequestUpdateOne) Mutation() *ReviewRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReviewRequestUpdate builder.
func (_u *ReviewRequestUpdateOne) Where(ps ...predicate.ReviewRequest) *ReviewRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewRequestUpdateOne) Select(field string, fields ...string) *ReviewRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReviewRequest entity.
func (_u *ReviewRequestUpdateOne) Save(ctx context.Context) (*ReviewRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewRequestUpdateOne) SaveX(ctx context.Context) *ReviewRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReviewRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reviewrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := reviewrequest.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ReviewRequest.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := reviewrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReviewRequest.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReviewRequestUpdateOne) sqlSave(ctx context.Context) (_node *ReviewRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reviewrequest.Table, reviewrequest.Columns, sqlgraph.NewFieldSpec(reviewrequest.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReviewRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reviewrequest.FieldID)
		for _, f := range fields {
			if !reviewrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reviewrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(reviewrequest.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reviewrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(reviewrequest.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(reviewrequest.FieldAppID, field.TypeInt, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(reviewrequest.FieldAppID, field.TypeInt)
	}
	if value, ok := _u.mutation.VersionID(); ok {
		_spec.SetField(reviewrequest.FieldVersionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionID(); ok {
		_spec.AddField(reviewrequest.FieldVersionID, field.TypeInt, value)
	}
	if _u.mutation.VersionIDCleared() {
		_spec.ClearField(reviewrequest.FieldVersionID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequesterID(); ok {
		_spec.SetField(reviewrequest.FieldRequesterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequesterID(); ok {
		_spec.AddField(reviewrequest.FieldRequesterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(reviewrequest.FieldReviewerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewerID(); ok {
		_spec.AddField(reviewrequest.FieldReviewerID, field.TypeInt, value)
	}
	if _u.mutation.ReviewerIDCleared() {
		_spec.ClearField(reviewrequest.FieldReviewerID, field.TypeInt)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(reviewrequest.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(reviewrequest.FieldReviewNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(reviewrequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(reviewrequest.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(reviewrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reviewrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ReviewRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reviewrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
