// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"lazycat.community/appstore/ent/storageconfig"
)

// StorageConfig is the model entity for the StorageConfig schema.
type StorageConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider storageconfig.Provider `json:"provider,omitempty"`
	// DeliveryMode holds the value of the "delivery_mode" field.
	DeliveryMode storageconfig.DeliveryMode `json:"delivery_mode,omitempty"`
	// LocalPath holds the value of the "local_path" field.
	LocalPath string `json:"local_path,omitempty"`
	// EndpointURL holds the value of the "endpoint_url" field.
	EndpointURL string `json:"endpoint_url,omitempty"`
	// BucketName holds the value of the "bucket_name" field.
	BucketName string `json:"bucket_name,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// PathStyle holds the value of the "path_style" field.
	PathStyle bool `json:"path_style,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// RootPrefix holds the value of the "root_prefix" field.
	RootPrefix string `json:"root_prefix,omitempty"`
	// AccessKeyID holds the value of the "access_key_id" field.
	AccessKeyID string `json:"-"`
	// SecretAccessKey holds the value of the "secret_access_key" field.
	SecretAccessKey string `json:"-"`
	// WebdavUsername holds the value of the "webdav_username" field.
	WebdavUsername string `json:"webdav_username,omitempty"`
	// WebdavPassword holds the value of the "webdav_password" field.
	WebdavPassword string `json:"-"`
	// PublicBaseURL holds the value of the "public_base_url" field.
	PublicBaseURL string `json:"public_base_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StorageConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storageconfig.FieldPathStyle:
			values[i] = new(sql.NullBool)
		case storageconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case storageconfig.FieldKey, storageconfig.FieldName, storageconfig.FieldProvider, storageconfig.FieldDeliveryMode, storageconfig.FieldLocalPath, storageconfig.FieldEndpointURL, storageconfig.FieldBucketName, storageconfig.FieldRegion, storageconfig.FieldAccountID, storageconfig.FieldRootPrefix, storageconfig.FieldAccessKeyID, storageconfig.FieldSecretAccessKey, storageconfig.FieldWebdavUsername, storageconfig.FieldWebdavPassword, storageconfig.FieldPublicBaseURL:
			values[i] = new(sql.NullString)
		case storageconfig.FieldCreatedAt, storageconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StorageConfig fields.
func (_m *StorageConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storageconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case storageconfig.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case storageconfig.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case storageconfig.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = storageconfig.Provider(value.String)
			}
		case storageconfig.FieldDeliveryMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_mode", values[i])
			} else if value.Valid {
				_m.DeliveryMode = storageconfig.DeliveryMode(value.String)
			}
		case storageconfig.FieldLocalPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_path", values[i])
			} else if value.Valid {
				_m.LocalPath = value.String
			}
		case storageconfig.FieldEndpointURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint_url", values[i])
			} else if value.Valid {
				_m.EndpointURL = value.String
			}
		case storageconfig.FieldBucketName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_name", values[i])
			} else if value.Valid {
				_m.BucketName = value.String
			}
		case storageconfig.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case storageconfig.FieldPathStyle:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field path_style", values[i])
			} else if value.Valid {
				_m.PathStyle = value.Bool
			}
		case storageconfig.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case storageconfig.FieldRootPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field root_prefix", values[i])
			} else if value.Valid {
				_m.RootPrefix = value.String
			}
		case storageconfig.FieldAccessKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_key_id", values[i])
			} else if value.Valid {
				_m.AccessKeyID = value.String
			}
		case storageconfig.FieldSecretAccessKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_access_key", values[i])
			} else if value.Valid {
				_m.SecretAccessKey = value.String
			}
		case storageconfig.FieldWebdavUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field webdav_username", values[i])
			} else if value.Valid {
				_m.WebdavUsername = value.String
			}
		case storageconfig.FieldWebdavPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field webdav_password", values[i])
			} else if value.Valid {
				_m.WebdavPassword = value.String
			}
		case storageconfig.FieldPublicBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_base_url", values[i])
			} else if value.Valid {
				_m.PublicBaseURL = value.String
			}
		case storageconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case storageconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StorageConfig.
// This includes values selected through modifiers, order, etc.
func (_m *StorageConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StorageConfig.
// Note that you need to call StorageConfig.Unwrap() before calling this method if this StorageConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StorageConfig) Update() *StorageConfigUpdateOne {
	return NewStorageConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StorageConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StorageConfig) Unwrap() *StorageConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StorageConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StorageConfig) String() string {
	var builder strings.Builder
	builder.WriteString("StorageConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provider))
	builder.WriteString(", ")
	builder.WriteString("delivery_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeliveryMode))
	builder.WriteString(", ")
	builder.WriteString("local_path=")
	builder.WriteString(_m.LocalPath)
	builder.WriteString(", ")
	builder.WriteString("endpoint_url=")
	builder.WriteString(_m.EndpointURL)
	builder.WriteString(", ")
	builder.WriteString("bucket_name=")
	builder.WriteString(_m.BucketName)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("path_style=")
	builder.WriteString(fmt.Sprintf("%v", _m.PathStyle))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("root_prefix=")
	builder.WriteString(_m.RootPrefix)
	builder.WriteString(", ")
	builder.WriteString("access_key_id=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("secret_access_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("webdav_username=")
	builder.WriteString(_m.WebdavUsername)
	builder.WriteString(", ")
	builder.WriteString("webdav_password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("public_base_url=")
	builder.WriteString(_m.PublicBaseURL)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StorageConfigs is a parsable slice of StorageConfig.
type StorageConfigs []*StorageConfig
