// Code generated by ent, DO NOT EDIT.

package app

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the app type in the database.
	Label = "app"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldPackageID holds the string denoting the package_id field in the database.
	FieldPackageID = "package_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameI18nJSON holds the string denoting the name_i18n_json field in the database.
	FieldNameI18nJSON = "name_i18n_json"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldSummaryI18nJSON holds the string denoting the summary_i18n_json field in the database.
	FieldSummaryI18nJSON = "summary_i18n_json"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldDescriptionI18nJSON holds the string denoting the description_i18n_json field in the database.
	FieldDescriptionI18nJSON = "description_i18n_json"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldHomepage holds the string denoting the homepage field in the database.
	FieldHomepage = "homepage"
	// FieldLicense holds the string denoting the license field in the database.
	FieldLicense = "license"
	// FieldMinOsVersion holds the string denoting the min_os_version field in the database.
	FieldMinOsVersion = "min_os_version"
	// FieldIconURL holds the string denoting the icon_url field in the database.
	FieldIconURL = "icon_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAllowUnreviewedUpdates holds the string denoting the allow_unreviewed_updates field in the database.
	FieldAllowUnreviewedUpdates = "allow_unreviewed_updates"
	// FieldCommentsEnabled holds the string denoting the comments_enabled field in the database.
	FieldCommentsEnabled = "comments_enabled"
	// FieldEmailNotificationsEnabled holds the string denoting the email_notifications_enabled field in the database.
	FieldEmailNotificationsEnabled = "email_notifications_enabled"
	// FieldInstallPasswordHash holds the string denoting the install_password_hash field in the database.
	FieldInstallPasswordHash = "install_password_hash"
	// FieldDownloadCount holds the string denoting the download_count field in the database.
	FieldDownloadCount = "download_count"
	// FieldVersionRetentionCount holds the string denoting the version_retention_count field in the database.
	FieldVersionRetentionCount = "version_retention_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the app in the database.
	Table = "apps"
)

// Columns holds all SQL columns for app fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldCategoryID,
	FieldPackageID,
	FieldName,
	FieldNameI18nJSON,
	FieldSlug,
	FieldSummary,
	FieldSummaryI18nJSON,
	FieldDescription,
	FieldDescriptionI18nJSON,
	FieldAuthor,
	FieldHomepage,
	FieldLicense,
	FieldMinOsVersion,
	FieldIconURL,
	FieldStatus,
	FieldAllowUnreviewedUpdates,
	FieldCommentsEnabled,
	FieldEmailNotificationsEnabled,
	FieldInstallPasswordHash,
	FieldDownloadCount,
	FieldVersionRetentionCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PackageIDValidator is a validator for the "package_id" field. It is called by the builders before save.
	PackageIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultNameI18nJSON holds the default value on creation for the "name_i18n_json" field.
	DefaultNameI18nJSON string
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultSummary holds the default value on creation for the "summary" field.
	DefaultSummary string
	// DefaultSummaryI18nJSON holds the default value on creation for the "summary_i18n_json" field.
	DefaultSummaryI18nJSON string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultDescriptionI18nJSON holds the default value on creation for the "description_i18n_json" field.
	DefaultDescriptionI18nJSON string
	// DefaultAuthor holds the default value on creation for the "author" field.
	DefaultAuthor string
	// DefaultHomepage holds the default value on creation for the "homepage" field.
	DefaultHomepage string
	// DefaultLicense holds the default value on creation for the "license" field.
	DefaultLicense string
	// DefaultMinOsVersion holds the default value on creation for the "min_os_version" field.
	DefaultMinOsVersion string
	// DefaultAllowUnreviewedUpdates holds the default value on creation for the "allow_unreviewed_updates" field.
	DefaultAllowUnreviewedUpdates bool
	// DefaultCommentsEnabled holds the default value on creation for the "comments_enabled" field.
	DefaultCommentsEnabled bool
	// DefaultEmailNotificationsEnabled holds the default value on creation for the "email_notifications_enabled" field.
	DefaultEmailNotificationsEnabled bool
	// DefaultInstallPasswordHash holds the default value on creation for the "install_password_hash" field.
	DefaultInstallPasswordHash string
	// DefaultDownloadCount holds the default value on creation for the "download_count" field.
	DefaultDownloadCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusDRAFT    Status = "DRAFT"
	StatusPENDING  Status = "PENDING"
	StatusAPPROVED Status = "APPROVED"
	StatusREJECTED Status = "REJECTED"
	StatusUNLISTED Status = "UNLISTED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDRAFT, StatusPENDING, StatusAPPROVED, StatusREJECTED, StatusUNLISTED:
		return nil
	default:
		return fmt.Errorf("app: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the App queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// ByPackageID orders the results by the package_id field.
func ByPackageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameI18nJSON orders the results by the name_i18n_json field.
func ByNameI18nJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameI18nJSON, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// BySummaryI18nJSON orders the results by the summary_i18n_json field.
func BySummaryI18nJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummaryI18nJSON, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByDescriptionI18nJSON orders the results by the description_i18n_json field.
func ByDescriptionI18nJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescriptionI18nJSON, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByHomepage orders the results by the homepage field.
func ByHomepage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHomepage, opts...).ToFunc()
}

// ByLicense orders the results by the license field.
func ByLicense(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicense, opts...).ToFunc()
}

// ByMinOsVersion orders the results by the min_os_version field.
func ByMinOsVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinOsVersion, opts...).ToFunc()
}

// ByIconURL orders the results by the icon_url field.
func ByIconURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIconURL, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAllowUnreviewedUpdates orders the results by the allow_unreviewed_updates field.
func ByAllowUnreviewedUpdates(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowUnreviewedUpdates, opts...).ToFunc()
}

// ByCommentsEnabled orders the results by the comments_enabled field.
func ByCommentsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommentsEnabled, opts...).ToFunc()
}

// ByEmailNotificationsEnabled orders the results by the email_notifications_enabled field.
func ByEmailNotificationsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailNotificationsEnabled, opts...).ToFunc()
}

// ByInstallPasswordHash orders the results by the install_password_hash field.
func ByInstallPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallPasswordHash, opts...).ToFunc()
}

// ByDownloadCount orders the results by the download_count field.
func ByDownloadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadCount, opts...).ToFunc()
}

// ByVersionRetentionCount orders the results by the version_retention_count field.
func ByVersionRetentionCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionRetentionCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
