// Code generated by ent, DO NOT EDIT.

package app

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"lazycat.community/appstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.App {
	return predicate.App(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.App {
	return predicate.App(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldOwnerID, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCategoryID, v))
}

// PackageID applies equality check predicate on the "package_id" field. It's identical to PackageIDEQ.
func PackageID(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldPackageID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// NameI18nJSON applies equality check predicate on the "name_i18n_json" field. It's identical to NameI18nJSONEQ.
func NameI18nJSON(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldNameI18nJSON, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSlug, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSummary, v))
}

// SummaryI18nJSON applies equality check predicate on the "summary_i18n_json" field. It's identical to SummaryI18nJSONEQ.
func SummaryI18nJSON(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSummaryI18nJSON, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDescription, v))
}

// DescriptionI18nJSON applies equality check predicate on the "description_i18n_json" field. It's identical to DescriptionI18nJSONEQ.
func DescriptionI18nJSON(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDescriptionI18nJSON, v))
}

// Author applies equality check predicate on the "author" field. It's identical to AuthorEQ.
func Author(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAuthor, v))
}

// Homepage applies equality check predicate on the "homepage" field. It's identical to HomepageEQ.
func Homepage(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldHomepage, v))
}

// License applies equality check predicate on the "license" field. It's identical to LicenseEQ.
func License(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldLicense, v))
}

// MinOsVersion applies equality check predicate on the "min_os_version" field. It's identical to MinOsVersionEQ.
func MinOsVersion(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldMinOsVersion, v))
}

// IconURL applies equality check predicate on the "icon_url" field. It's identical to IconURLEQ.
func IconURL(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldIconURL, v))
}

// AllowUnreviewedUpdates applies equality check predicate on the "allow_unreviewed_updates" field. It's identical to AllowUnreviewedUpdatesEQ.
func AllowUnreviewedUpdates(v bool) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAllowUnreviewedUpdates, v))
}

// CommentsEnabled applies equality check predicate on the "comments_enabled" field. It's identical to CommentsEnabledEQ.
func CommentsEnabled(v bool) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCommentsEnabled, v))
}

// EmailNotificationsEnabled applies equality check predicate on the "email_notifications_enabled" field. It's identical to EmailNotificationsEnabledEQ.
func EmailNotificationsEnabled(v bool) predicate.App {
	return predicate.App(sql.FieldEQ(FieldEmailNotificationsEnabled, v))
}

// InstallPasswordHash applies equality check predicate on the "install_password_hash" field. It's identical to InstallPasswordHashEQ.
func InstallPasswordHash(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldInstallPasswordHash, v))
}

// DownloadCount applies equality check predicate on the "download_count" field. It's identical to DownloadCountEQ.
func DownloadCount(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDownloadCount, v))
}

// VersionRetentionCount applies equality check predicate on the "version_retention_count" field. It's identical to VersionRetentionCountEQ.
func VersionRetentionCount(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldVersionRetentionCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v int) predicate.App {
	return predicate.App(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v int) predicate.App {
	return predicate.App(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldOwnerID, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDGT applies the GT predicate on the "category_id" field.
func CategoryIDGT(v int) predicate.App {
	return predicate.App(sql.FieldGT(FieldCategoryID, v))
}

// CategoryIDGTE applies the GTE predicate on the "category_id" field.
func CategoryIDGTE(v int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCategoryID, v))
}

// CategoryIDLT applies the LT predicate on the "category_id" field.
func CategoryIDLT(v int) predicate.App {
	return predicate.App(sql.FieldLT(FieldCategoryID, v))
}

// CategoryIDLTE applies the LTE predicate on the "category_id" field.
func CategoryIDLTE(v int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCategoryID, v))
}

// CategoryIDIsNil applies the IsNil predicate on the "category_id" field.
func CategoryIDIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldCategoryID))
}

// CategoryIDNotNil applies the NotNil predicate on the "category_id" field.
func CategoryIDNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldCategoryID))
}

// PackageIDEQ applies the EQ predicate on the "package_id" field.
func PackageIDEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldPackageID, v))
}

// PackageIDNEQ applies the NEQ predicate on the "package_id" field.
func PackageIDNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldPackageID, v))
}

// PackageIDIn applies the In predicate on the "package_id" field.
func PackageIDIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldPackageID, vs...))
}

// PackageIDNotIn applies the NotIn predicate on the "package_id" field.
func PackageIDNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldPackageID, vs...))
}

// PackageIDGT applies the GT predicate on the "package_id" field.
func PackageIDGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldPackageID, v))
}

// PackageIDGTE applies the GTE predicate on the "package_id" field.
func PackageIDGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldPackageID, v))
}

// PackageIDLT applies the LT predicate on the "package_id" field.
func PackageIDLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldPackageID, v))
}

// PackageIDLTE applies the LTE predicate on the "package_id" field.
func PackageIDLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldPackageID, v))
}

// PackageIDContains applies the Contains predicate on the "package_id" field.
func PackageIDContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldPackageID, v))
}

// PackageIDHasPrefix applies the HasPrefix predicate on the "package_id" field.
func PackageIDHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldPackageID, v))
}

// PackageIDHasSuffix applies the HasSuffix predicate on the "package_id" field.
func PackageIDHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldPackageID, v))
}

// PackageIDEqualFold applies the EqualFold predicate on the "package_id" field.
func PackageIDEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldPackageID, v))
}

// PackageIDContainsFold applies the ContainsFold predicate on the "package_id" field.
func PackageIDContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldPackageID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldName, v))
}

// NameI18nJSONEQ applies the EQ predicate on the "name_i18n_json" field.
func NameI18nJSONEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldNameI18nJSON, v))
}

// NameI18nJSONNEQ applies the NEQ predicate on the "name_i18n_json" field.
func NameI18nJSONNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldNameI18nJSON, v))
}

// NameI18nJSONIn applies the In predicate on the "name_i18n_json" field.
func NameI18nJSONIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldNameI18nJSON, vs...))
}

// NameI18nJSONNotIn applies the NotIn predicate on the "name_i18n_json" field.
func NameI18nJSONNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldNameI18nJSON, vs...))
}

// NameI18nJSONGT applies the GT predicate on the "name_i18n_json" field.
func NameI18nJSONGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldNameI18nJSON, v))
}

// NameI18nJSONGTE applies the GTE predicate on the "name_i18n_json" field.
func NameI18nJSONGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldNameI18nJSON, v))
}

// NameI18nJSONLT applies the LT predicate on the "name_i18n_json" field.
func NameI18nJSONLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldNameI18nJSON, v))
}

// NameI18nJSONLTE applies the LTE predicate on the "name_i18n_json" field.
func NameI18nJSONLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldNameI18nJSON, v))
}

// NameI18nJSONContains applies the Contains predicate on the "name_i18n_json" field.
func NameI18nJSONContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldNameI18nJSON, v))
}

// NameI18nJSONHasPrefix applies the HasPrefix predicate on the "name_i18n_json" field.
func NameI18nJSONHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldNameI18nJSON, v))
}

// NameI18nJSONHasSuffix applies the HasSuffix predicate on the "name_i18n_json" field.
func NameI18nJSONHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldNameI18nJSON, v))
}

// NameI18nJSONEqualFold applies the EqualFold predicate on the "name_i18n_json" field.
func NameI18nJSONEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldNameI18nJSON, v))
}

// NameI18nJSONContainsFold applies the ContainsFold predicate on the "name_i18n_json" field.
func NameI18nJSONContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldNameI18nJSON, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldSlug, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldSummary, v))
}

// SummaryI18nJSONEQ applies the EQ predicate on the "summary_i18n_json" field.
func SummaryI18nJSONEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONNEQ applies the NEQ predicate on the "summary_i18n_json" field.
func SummaryI18nJSONNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONIn applies the In predicate on the "summary_i18n_json" field.
func SummaryI18nJSONIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldSummaryI18nJSON, vs...))
}

// SummaryI18nJSONNotIn applies the NotIn predicate on the "summary_i18n_json" field.
func SummaryI18nJSONNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldSummaryI18nJSON, vs...))
}

// SummaryI18nJSONGT applies the GT predicate on the "summary_i18n_json" field.
func SummaryI18nJSONGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONGTE applies the GTE predicate on the "summary_i18n_json" field.
func SummaryI18nJSONGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONLT applies the LT predicate on the "summary_i18n_json" field.
func SummaryI18nJSONLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONLTE applies the LTE predicate on the "summary_i18n_json" field.
func SummaryI18nJSONLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONContains applies the Contains predicate on the "summary_i18n_json" field.
func SummaryI18nJSONContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONHasPrefix applies the HasPrefix predicate on the "summary_i18n_json" field.
func SummaryI18nJSONHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONHasSuffix applies the HasSuffix predicate on the "summary_i18n_json" field.
func SummaryI18nJSONHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONEqualFold applies the EqualFold predicate on the "summary_i18n_json" field.
func SummaryI18nJSONEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldSummaryI18nJSON, v))
}

// SummaryI18nJSONContainsFold applies the ContainsFold predicate on the "summary_i18n_json" field.
func SummaryI18nJSONContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldSummaryI18nJSON, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldDescription, v))
}

// DescriptionI18nJSONEQ applies the EQ predicate on the "description_i18n_json" field.
func DescriptionI18nJSONEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONNEQ applies the NEQ predicate on the "description_i18n_json" field.
func DescriptionI18nJSONNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONIn applies the In predicate on the "description_i18n_json" field.
func DescriptionI18nJSONIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldDescriptionI18nJSON, vs...))
}

// DescriptionI18nJSONNotIn applies the NotIn predicate on the "description_i18n_json" field.
func DescriptionI18nJSONNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldDescriptionI18nJSON, vs...))
}

// DescriptionI18nJSONGT applies the GT predicate on the "description_i18n_json" field.
func DescriptionI18nJSONGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONGTE applies the GTE predicate on the "description_i18n_json" field.
func DescriptionI18nJSONGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONLT applies the LT predicate on the "description_i18n_json" field.
func DescriptionI18nJSONLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONLTE applies the LTE predicate on the "description_i18n_json" field.
func DescriptionI18nJSONLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONContains applies the Contains predicate on the "description_i18n_json" field.
func DescriptionI18nJSONContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONHasPrefix applies the HasPrefix predicate on the "description_i18n_json" field.
func DescriptionI18nJSONHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONHasSuffix applies the HasSuffix predicate on the "description_i18n_json" field.
func DescriptionI18nJSONHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONEqualFold applies the EqualFold predicate on the "description_i18n_json" field.
func DescriptionI18nJSONEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldDescriptionI18nJSON, v))
}

// DescriptionI18nJSONContainsFold applies the ContainsFold predicate on the "description_i18n_json" field.
func DescriptionI18nJSONContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldDescriptionI18nJSON, v))
}

// AuthorEQ applies the EQ predicate on the "author" field.
func AuthorEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAuthor, v))
}

// AuthorNEQ applies the NEQ predicate on the "author" field.
func AuthorNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldAuthor, v))
}

// AuthorIn applies the In predicate on the "author" field.
func AuthorIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldAuthor, vs...))
}

// AuthorNotIn applies the NotIn predicate on the "author" field.
func AuthorNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldAuthor, vs...))
}

// AuthorGT applies the GT predicate on the "author" field.
func AuthorGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldAuthor, v))
}

// AuthorGTE applies the GTE predicate on the "author" field.
func AuthorGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldAuthor, v))
}

// AuthorLT applies the LT predicate on the "author" field.
func AuthorLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldAuthor, v))
}

// AuthorLTE applies the LTE predicate on the "author" field.
func AuthorLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldAuthor, v))
}

// AuthorContains applies the Contains predicate on the "author" field.
func AuthorContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldAuthor, v))
}

// AuthorHasPrefix applies the HasPrefix predicate on the "author" field.
func AuthorHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldAuthor, v))
}

// AuthorHasSuffix applies the HasSuffix predicate on the "author" field.
func AuthorHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldAuthor, v))
}

// AuthorEqualFold applies the EqualFold predicate on the "author" field.
func AuthorEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldAuthor, v))
}

// AuthorContainsFold applies the ContainsFold predicate on the "author" field.
func AuthorContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldAuthor, v))
}

// HomepageEQ applies the EQ predicate on the "homepage" field.
func HomepageEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldHomepage, v))
}

// HomepageNEQ applies the NEQ predicate on the "homepage" field.
func HomepageNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldHomepage, v))
}

// HomepageIn applies the In predicate on the "homepage" field.
func HomepageIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldHomepage, vs...))
}

// HomepageNotIn applies the NotIn predicate on the "homepage" field.
func HomepageNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldHomepage, vs...))
}

// HomepageGT applies the GT predicate on the "homepage" field.
func HomepageGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldHomepage, v))
}

// HomepageGTE applies the GTE predicate on the "homepage" field.
func HomepageGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldHomepage, v))
}

// HomepageLT applies the LT predicate on the "homepage" field.
func HomepageLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldHomepage, v))
}

// HomepageLTE applies the LTE predicate on the "homepage" field.
func HomepageLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldHomepage, v))
}

// HomepageContains applies the Contains predicate on the "homepage" field.
func HomepageContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldHomepage, v))
}

// HomepageHasPrefix applies the HasPrefix predicate on the "homepage" field.
func HomepageHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldHomepage, v))
}

// HomepageHasSuffix applies the HasSuffix predicate on the "homepage" field.
func HomepageHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldHomepage, v))
}

// HomepageEqualFold applies the EqualFold predicate on the "homepage" field.
func HomepageEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldHomepage, v))
}

// HomepageContainsFold applies the ContainsFold predicate on the "homepage" field.
func HomepageContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldHomepage, v))
}

// LicenseEQ applies the EQ predicate on the "license" field.
func LicenseEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldLicense, v))
}

// LicenseNEQ applies the NEQ predicate on the "license" field.
func LicenseNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldLicense, v))
}

// LicenseIn applies the In predicate on the "license" field.
func LicenseIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldLicense, vs...))
}

// LicenseNotIn applies the NotIn predicate on the "license" field.
func LicenseNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldLicense, vs...))
}

// LicenseGT applies the GT predicate on the "license" field.
func LicenseGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldLicense, v))
}

// LicenseGTE applies the GTE predicate on the "license" field.
func LicenseGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldLicense, v))
}

// LicenseLT applies the LT predicate on the "license" field.
func LicenseLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldLicense, v))
}

// LicenseLTE applies the LTE predicate on the "license" field.
func LicenseLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldLicense, v))
}

// LicenseContains applies the Contains predicate on the "license" field.
func LicenseContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldLicense, v))
}

// LicenseHasPrefix applies the HasPrefix predicate on the "license" field.
func LicenseHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldLicense, v))
}

// LicenseHasSuffix applies the HasSuffix predicate on the "license" field.
func LicenseHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldLicense, v))
}

// LicenseEqualFold applies the EqualFold predicate on the "license" field.
func LicenseEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldLicense, v))
}

// LicenseContainsFold applies the ContainsFold predicate on the "license" field.
func LicenseContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldLicense, v))
}

// MinOsVersionEQ applies the EQ predicate on the "min_os_version" field.
func MinOsVersionEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldMinOsVersion, v))
}

// MinOsVersionNEQ applies the NEQ predicate on the "min_os_version" field.
func MinOsVersionNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldMinOsVersion, v))
}

// MinOsVersionIn applies the In predicate on the "min_os_version" field.
func MinOsVersionIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldMinOsVersion, vs...))
}

// MinOsVersionNotIn applies the NotIn predicate on the "min_os_version" field.
func MinOsVersionNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldMinOsVersion, vs...))
}

// MinOsVersionGT applies the GT predicate on the "min_os_version" field.
func MinOsVersionGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldMinOsVersion, v))
}

// MinOsVersionGTE applies the GTE predicate on the "min_os_version" field.
func MinOsVersionGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldMinOsVersion, v))
}

// MinOsVersionLT applies the LT predicate on the "min_os_version" field.
func MinOsVersionLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldMinOsVersion, v))
}

// MinOsVersionLTE applies the LTE predicate on the "min_os_version" field.
func MinOsVersionLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldMinOsVersion, v))
}

// MinOsVersionContains applies the Contains predicate on the "min_os_version" field.
func MinOsVersionContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldMinOsVersion, v))
}

// MinOsVersionHasPrefix applies the HasPrefix predicate on the "min_os_version" field.
func MinOsVersionHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldMinOsVersion, v))
}

// MinOsVersionHasSuffix applies the HasSuffix predicate on the "min_os_version" field.
func MinOsVersionHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldMinOsVersion, v))
}

// MinOsVersionEqualFold applies the EqualFold predicate on the "min_os_version" field.
func MinOsVersionEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldMinOsVersion, v))
}

// MinOsVersionContainsFold applies the ContainsFold predicate on the "min_os_version" field.
func MinOsVersionContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldMinOsVersion, v))
}

// IconURLEQ applies the EQ predicate on the "icon_url" field.
func IconURLEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldIconURL, v))
}

// IconURLNEQ applies the NEQ predicate on the "icon_url" field.
func IconURLNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldIconURL, v))
}

// IconURLIn applies the In predicate on the "icon_url" field.
func IconURLIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldIconURL, vs...))
}

// IconURLNotIn applies the NotIn predicate on the "icon_url" field.
func IconURLNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldIconURL, vs...))
}

// IconURLGT applies the GT predicate on the "icon_url" field.
func IconURLGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldIconURL, v))
}

// IconURLGTE applies the GTE predicate on the "icon_url" field.
func IconURLGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldIconURL, v))
}

// IconURLLT applies the LT predicate on the "icon_url" field.
func IconURLLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldIconURL, v))
}

// IconURLLTE applies the LTE predicate on the "icon_url" field.
func IconURLLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldIconURL, v))
}

// IconURLContains applies the Contains predicate on the "icon_url" field.
func IconURLContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldIconURL, v))
}

// IconURLHasPrefix applies the HasPrefix predicate on the "icon_url" field.
func IconURLHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldIconURL, v))
}

// IconURLHasSuffix applies the HasSuffix predicate on the "icon_url" field.
func IconURLHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldIconURL, v))
}

// IconURLIsNil applies the IsNil predicate on the "icon_url" field.
func IconURLIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldIconURL))
}

// IconURLNotNil applies the NotNil predicate on the "icon_url" field.
func IconURLNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldIconURL))
}

// IconURLEqualFold applies the EqualFold predicate on the "icon_url" field.
func IconURLEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldIconURL, v))
}

// IconURLContainsFold applies the ContainsFold predicate on the "icon_url" field.
func IconURLContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldIconURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.App {
	return predicate.App(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.App {
	return predicate.App(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldStatus, vs...))
}

// AllowUnreviewedUpdatesEQ applies the EQ predicate on the "allow_unreviewed_updates" field.
func AllowUnreviewedUpdatesEQ(v bool) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAllowUnreviewedUpdates, v))
}

// AllowUnreviewedUpdatesNEQ applies the NEQ predicate on the "allow_unreviewed_updates" field.
func AllowUnreviewedUpdatesNEQ(v bool) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldAllowUnreviewedUpdates, v))
}

// CommentsEnabledEQ applies the EQ predicate on the "comments_enabled" field.
func CommentsEnabledEQ(v bool) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCommentsEnabled, v))
}

// CommentsEnabledNEQ applies the NEQ predicate on the "comments_enabled" field.
func CommentsEnabledNEQ(v bool) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCommentsEnabled, v))
}

// EmailNotificationsEnabledEQ applies the EQ predicate on the "email_notifications_enabled" field.
func EmailNotificationsEnabledEQ(v bool) predicate.App {
	return predicate.App(sql.FieldEQ(FieldEmailNotificationsEnabled, v))
}

// EmailNotificationsEnabledNEQ applies the NEQ predicate on the "email_notifications_enabled" field.
func EmailNotificationsEnabledNEQ(v bool) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldEmailNotificationsEnabled, v))
}

// InstallPasswordHashEQ applies the EQ predicate on the "install_password_hash" field.
func InstallPasswordHashEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldInstallPasswordHash, v))
}

// InstallPasswordHashNEQ applies the NEQ predicate on the "install_password_hash" field.
func InstallPasswordHashNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldInstallPasswordHash, v))
}

// InstallPasswordHashIn applies the In predicate on the "install_password_hash" field.
func InstallPasswordHashIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldInstallPasswordHash, vs...))
}

// InstallPasswordHashNotIn applies the NotIn predicate on the "install_password_hash" field.
func InstallPasswordHashNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldInstallPasswordHash, vs...))
}

// InstallPasswordHashGT applies the GT predicate on the "install_password_hash" field.
func InstallPasswordHashGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldInstallPasswordHash, v))
}

// InstallPasswordHashGTE applies the GTE predicate on the "install_password_hash" field.
func InstallPasswordHashGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldInstallPasswordHash, v))
}

// InstallPasswordHashLT applies the LT predicate on the "install_password_hash" field.
func InstallPasswordHashLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldInstallPasswordHash, v))
}

// InstallPasswordHashLTE applies the LTE predicate on the "install_password_hash" field.
func InstallPasswordHashLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldInstallPasswordHash, v))
}

// InstallPasswordHashContains applies the Contains predicate on the "install_password_hash" field.
func InstallPasswordHashContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldInstallPasswordHash, v))
}

// InstallPasswordHashHasPrefix applies the HasPrefix predicate on the "install_password_hash" field.
func InstallPasswordHashHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldInstallPasswordHash, v))
}

// InstallPasswordHashHasSuffix applies the HasSuffix predicate on the "install_password_hash" field.
func InstallPasswordHashHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldInstallPasswordHash, v))
}

// InstallPasswordHashEqualFold applies the EqualFold predicate on the "install_password_hash" field.
func InstallPasswordHashEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldInstallPasswordHash, v))
}

// InstallPasswordHashContainsFold applies the ContainsFold predicate on the "install_password_hash" field.
func InstallPasswordHashContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldInstallPasswordHash, v))
}

// DownloadCountEQ applies the EQ predicate on the "download_count" field.
func DownloadCountEQ(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDownloadCount, v))
}

// DownloadCountNEQ applies the NEQ predicate on the "download_count" field.
func DownloadCountNEQ(v int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldDownloadCount, v))
}

// DownloadCountIn applies the In predicate on the "download_count" field.
func DownloadCountIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldDownloadCount, vs...))
}

// DownloadCountNotIn applies the NotIn predicate on the "download_count" field.
func DownloadCountNotIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldDownloadCount, vs...))
}

// DownloadCountGT applies the GT predicate on the "download_count" field.
func DownloadCountGT(v int) predicate.App {
	return predicate.App(sql.FieldGT(FieldDownloadCount, v))
}

// DownloadCountGTE applies the GTE predicate on the "download_count" field.
func DownloadCountGTE(v int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldDownloadCount, v))
}

// DownloadCountLT applies the LT predicate on the "download_count" field.
func DownloadCountLT(v int) predicate.App {
	return predicate.App(sql.FieldLT(FieldDownloadCount, v))
}

// DownloadCountLTE applies the LTE predicate on the "download_count" field.
func DownloadCountLTE(v int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldDownloadCount, v))
}

// VersionRetentionCountEQ applies the EQ predicate on the "version_retention_count" field.
func VersionRetentionCountEQ(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldVersionRetentionCount, v))
}

// VersionRetentionCountNEQ applies the NEQ predicate on the "version_retention_count" field.
func VersionRetentionCountNEQ(v int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldVersionRetentionCount, v))
}

// VersionRetentionCountIn applies the In predicate on the "version_retention_count" field.
func VersionRetentionCountIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldVersionRetentionCount, vs...))
}

// VersionRetentionCountNotIn applies the NotIn predicate on the "version_retention_count" field.
func VersionRetentionCountNotIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldVersionRetentionCount, vs...))
}

// VersionRetentionCountGT applies the GT predicate on the "version_retention_count" field.
func VersionRetentionCountGT(v int) predicate.App {
	return predicate.App(sql.FieldGT(FieldVersionRetentionCount, v))
}

// VersionRetentionCountGTE applies the GTE predicate on the "version_retention_count" field.
func VersionRetentionCountGTE(v int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldVersionRetentionCount, v))
}

// VersionRetentionCountLT applies the LT predicate on the "version_retention_count" field.
func VersionRetentionCountLT(v int) predicate.App {
	return predicate.App(sql.FieldLT(FieldVersionRetentionCount, v))
}

// VersionRetentionCountLTE applies the LTE predicate on the "version_retention_count" field.
func VersionRetentionCountLTE(v int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldVersionRetentionCount, v))
}

// VersionRetentionCountIsNil applies the IsNil predicate on the "version_retention_count" field.
func VersionRetentionCountIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldVersionRetentionCount))
}

// VersionRetentionCountNotNil applies the NotNil predicate on the "version_retention_count" field.
func VersionRetentionCountNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldVersionRetentionCount))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.App) predicate.App {
	return predicate.App(sql.NotPredicates(p))
}
